### ISSUE TITLE
Return code dans le tableau de la liste de distribution

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#103]
@thibault Dans le tableau de la liste de distribution, la colonne "Return Code" ne s'appelle "que" "Code".
Je comprends qu'il y a le problème de l'affichage, donc je te propose de soit renommer en mettant "Return code" sur 2 lignes, soit en mettant simplement "RC".
Tu me dis ? Merci !

**Comment by thibault** [comment]
C'est fait.
