### ISSUE TITLE
Utilisateurs dans Phase

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#105]
@thibault 
Pourrais-tu s'il te plait créer les utilisateurs suivants et configurer les permissions comme suit : 

Rôle de Doc Controller
- dc1@phase.fr (name :  Document Controller 1) --> accès à l'organisation ACME avec les catégories Contractor Deliverables et Transmittals, mais pas Correspondence, ni Minutes of Meeting, et accès à l'organisation EPC2
- dc2@phase.fr (name : Document Controller 2) --> accès à l'organisation ACME, juste aux catégories Correspondence et Minutes of Meeting, mais pas du tout accès à l'organisation à EPC2

Rôle de User
- user1@phase.fr (name : User 1) --> accès à l'organisation ACME avec les catégories Contractor Deliverables et Transmittals, mais pas Correspondence, ni Minutes of Meeting, et accès à l'organisation EPC2
- user2@phase.fr (name : User 2) --> accès à l'organisation ACME, juste aux catégories Correspondence et Minutes of Meeting, mais pas du tout accès à l'organisation à EPC2

**Comment by thibault** [comment]
@Talengi Fait.
