### ISSUE TITLE
Affichage des dates au format français dans le formulaire

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#107]
@thibault dans le formulaire de documents, le format de la "Revision date" est en français, alors que le format du champ "Created on" est en américain.

Est-il possible de tout mettre en français ?
Si tout mettre en Français est compliqué (notamment pour les tris croissant/décroissant dans la liste de docs), alors peut-on tout mettre en américain ?

Merci.

**Comment by thibault** [comment]
@Talengi Dans la mesure ou toute l'application est naturalisée en anglais, je pense qu'il vaut mieux également laisser les dates au format international.

La langue du site est une option globale, et si on veut afficher les dates en français, on va se retrouver avec un mélange des deux langues / formattages sur le site qui serait à mon avis préjudiciable.

Je vais passer le datepicker en anglais si ça te va.

**Comment by Talengi** [comment]
@thibault OK on met tout en américain. Assure toi que ça se répercute bien partout stp !
Merci.
