### ISSUE TITLE
Affichage du Return Code dans le champ du formulaire

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#111]
@thibault Lorsqu'une revue est terminée et que le Leader ou l'Approver on indiqué le Return Code, celui-ci apparait bien dans le tableau de la liste de distribution, mais on ne le fait pas apparaitre dans le champ "Return Code" du formulaire.
Peux-tu s'il te plait faire la modif afin que le return code de la dernière personne ayant revu le doc (Leader ou Approver, en fonction de la liste de distribution qui peut être sur 2 ou 3 étapes) apparaisse dans le champs Return Code du formulaire de document ?
Merci !

**Comment by thibault** [comment]
@Talengi Je reformule pour être certain d'avoir bien compris.

Dans le formulaire de document, il y a déjà un ancien champ « return code » qui peut être modifié à la main.

Si je comprends bien, tu veux que :
* ce champ passe en lecture seule
* sa valeur soit celle du dernier « return code » soumis par un leader ou approver lors d'une revue

C'est ça ?

**Comment by Talengi** [comment]
@thibault Oui c'est exact
