### ISSUE TITLE
Impossible d'ouvrir des documents dans l'organisation EPC2

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#114]
@thibault Je n'arrive pas à ouvrir de documents depuis l'orga EPC2. Peux-tu regarder pourquoi stp ?
merci

**Comment by thibault** [comment]
@Talengi Peux-tu préciser le problème, car je ne reproduits pas ? C'est peut-être corrigé avec les autres bugs « oops ».

**Comment by Talengi** [comment]
@thibault en effet ça remarche. Tu peux fermer.
