### ISSUE TITLE
Bug dans les remarques en faisant une mention

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#115]
@thibault Je suis dans le formulaire du document FAC09001-CTR-001-PRT-LAY-0186.
Je viens de finir de le revoir en tant que doc controller et je suis arrivé dans le formulaire via le lien dans mes notifications.
Si je mets une remarque sans mention, tout marche. Si je mentionne "user", je me retrouve avec le message posté 2 fois.

Si je supprime la remarque en double, elle disparait bien du compteur de l'icone "Remarks". Mais si après je rentre à nouveau dans les remarques et que je poste à nouveau une remarque en mentionnant "user", les remarques supprimées réapparaissent.

Peux-tu regarder stp ?

**Comment by thibault** [comment]
J'ai suivi ces étapes, mais je ne reproduits pas le problème. Est-ce qu'il apparait systématiquement chez toi ?

**Comment by Talengi** [comment]
@thibault Effectivement je ne reproduis pas non plus. C'est bizarre car c'était systématique hier. On met en attente pour le moment et je vais réessayer par ma suite

**Comment by Talengi** [comment]
@thibault J'ai refait des essais et je ne reproduis pas, tout fonctionne bien. C'est assez étrange car je n'ai pas rêvé ! :)
Je ferme le ticket et on le rouvre si jamais on voit un truc bizarre plus tard. Pour le moment, tout est OK.
