### ISSUE TITLE
Suppression des remarques avec mentions et lien avec les notifications

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#117]
@thibault Tu peux regarder : si je mentionne un utilisateur dans les remarques et que je supprime ensuite la remarque, est-ce que la notification va rester chez l'utilisateur mentionné (et donc pointer vers une remarque qui n'existe plus) ?
Si c'est bien le comportement aujourd'hui, peux-tu modifier le code afin que si une remarque avec mention est supprimée, l'utilisateur mentionné ne trouve pas la notification ?
Merci.

**Comment by thibault** [comment]
@Talengi Quelques remarques par rapport à ça.

J'aurai tendance à dire que ce ticket pourrais poser des problèmes d'un point de vue fonctionnel et technique.

D'un point de vue fonctionnel, je pense que supprimer des notifications déjà envoyées peut prêter à confusion. Et si l'utilisateur a vu la notif, et qu'il la cherche par la suite mais ne la trouve plus ?

On peut bien sûr la supprimer uniquement si elle n'a pas encore été vue, mais on multiplie les cas particuliers.

D'un point de vue technique, les notifications sont des messages utilisables globalement par tous les éléments de l'application, et devraient rester indépendants. Une fois une notif créée, il n'y a pas de lien entre elle et l'événement qui a déclenché sa création. C'est une fonctionnalité qui permet de gérer les notifs de manière optimale, éventuellement de les stocker un jour dans un autre data store (rabbitmq ? memcached ?).

Je peux proposer une solution alternative, basée sur le fonctionnement actuel de pas mal de sites existants : quand un utilisateur supprime une notification, plutôt que de la supprimer complètement, on la remplace par un simple texte « supprimé ».

Ça permet
- à un utilisateur de pouvoir supprimer un message
- de ne pas « casser » des conversations existantes qui pourraient changer de sens si un ou plusieurs messages se mettent à disparaître sans traces
- de ne pas perturber l'utilisateur qui a reçu une notification de mention mais ne trouve pas la notification correspondante ?

À vrai dire, c'est ma faute, j'aurais déjà du suggérer ce développement quand on a abordé la suppression des notifs.

Qu'en penses-tu ?

**Comment by Talengi** [comment]
@thibault OK faisons comme ça !
