### ISSUE TITLE
Manque la contraine unique sur les revues

### ISSUE THREAD

**Issue by thibault** [Talengi/phase#119]
Il n'est a priori pas possible pour un même utilisateur d'être cité deux fois dans la liste de distribution (e.g avec deux rôles différents).

Le code compte parfois sur ce prérequis, mais ce dernier n'est pas forcé d'un point de vue technique.

J'ai donc ajouté une contrainte pour garantir l'intégrité des données.

Pour le moment, si le cas se présente, la création de revue plante. Il faudrait ajouter un message d'erreur plus correct.

**Comment by Talengi** [comment]
@thibault Je confirme qu'un utilisateur devrait n'être que sur un seul rôle au sein d'une liste de distribution

**Comment by thibault** [comment]
Il existait de nombreux documents avec des membres en double dans la liste de distribution, ce qui empêchait la mise à jour du schéma de la base de données. J'ai pris la liberté d'écrire un script qui a annulé la revue de toutes les révisions concernées (une vingtaine environ). Il est donc possible que tu constates que des documents qui étaient en revue ne le sont plus, c'était dû à un traitement ponctuel.
