### ISSUE TITLE
Cache pas vidé pour les listes de valeurs

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#120]
@thibault Les listes de valeurs sans libellés sont toujours là. Il faut vraiment les faire disparaitre au plus vite. Tu peux voir cela demain stp ?
Merci.

**Comment by thibault** [comment]
@Talengi Les listes me paraissent cohérentes avec ce qui est en base de donnée. Peux-tu me dire à quel endroit tu vois une différence pour que je regarde ?

**Comment by Talengi** [comment]
@thibault Mise à jour des values lists. Peux-tu vider le cache stp ?
Merci !
