### ISSUE TITLE
Impossible de télécharger des fichiers depuis la liste de documents

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#121]
@thibault Je suis dans la liste de documents et j'essaye de télécharger des fichiers avec le bouton "Download". J'arrive sur une page qui me dit "This is not what you are looking for" et ça ne marche pas.
Peux-tu corriger stp ?

**Comment by thibault** [comment]
@Talengi Je ne reproduits pas. Peux tu préciser les étapes suivies pour arriver au problème ?

**Comment by Talengi** [comment]
@thibault En effet, je ne reproduis pas le problème non plus. Je ferme le ticket.
