### ISSUE TITLE
Ordre des valeurs dans les menus déroulants

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#127]
@thibault C'est bon pour les caches et les anciennes valeurs sans libellés, mais à présent, les valeurs restantes sont listées dans le désordre.
Comment les réordonner dans un ordre alphabétique ou croissant ?
Merci !

**Comment by thibault** [comment]
@Talengi Tu as un champ « order » pour chaque liste de valeur. Je peux aussi rajouter un tri par ordre alphabetique par défaut, mais faut il le faire sur l'index ou sur le label de la valeur ?

**Comment by Talengi** [comment]
@thibault dans le champ "order" je mets 1, 2, 3, 4, 5, etc. à chaque fois pour indiquer l'ordre de tri ?
Ok pour le tri par défaut et tu le mets sur l'index.
Merci !

**Comment by thibault** [comment]
@Talengi Oui, c'est ça. Et c'est fait.
