### ISSUE TITLE
Affichage du menu déroulant Discipline

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#129]
@thibault Contrairement aux autres menus déroulants, lorsque tu ouvres le menu "Discipline", l'ascenceur vertical n'est pas positionné tout en haut. Il faut que tu remontes pour afficher la 1ère discipline.
Je suis sur Firefox/Windows 7.

Est-ce que tu reproduis ?
Merci.

**Comment by Talengi** [comment]
@thibault Je précise : certains menus s'ouvrent avec l'ascenceur tout en haut, d'autres s'ouvrent avec l'ascenceur positionné au niveau de la valeur sélectionnée (sur un document que l'on édite par exemple et qui a donc déjà une valeur sélectionnée).

**Comment by thibault** [comment]
@Talengi Dans l'état actuel des choses, le champ « discipline » est défini avec une valeur par défaut à « PCS ». D'autres champs ont aussi des valeurs par défaut. C'est pour ça que ces valeurs sont pré-selectionnées quand tu créé un document. Est-ce ça qui pose problème ?

À part ça, les listes de sélection n'ont absolument pas été modifés, ce sont les widgets par défaut du navigateur.

**Comment by Talengi** [comment]
@thibault Ok ça explique cela. Pas de souci on laisse en l'état pour le moment et ça permet de montrer effectivement que l'on peut avoir différents comportements dans les menus déroulants. Je ferme le ticket.
