### ISSUE TITLE
Nombre d'items indiqué dans les Priorities à revoir et nombre réel de documents listés

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#134]
@thibault Je suis connecté en tant que Doc Controller et lorsque je vais dans le menu "Reviews", je vois 10 documents en "Priorities", mais lorsque je rentre dans cette section, il n'y en a que 6 de listés.
Peux-tu regarder stp ?
Merci.

**Comment by thibault** [comment]
@Talengi J'ai trouvé. C'est dû au fait que le doc controller apparait plusieurs fois dans les listes de certains documents, ce qui fausse les compte.

Ça ne devrait pas arriver, mais il n'y a pour l'instant pas de contraine technique. Cf. #119.

Je ferme ce ticket car il sera résolu tout seul en même temps que le #119.
