### ISSUE TITLE
Cancel review depuis la section de review

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#136]
@thibault Lorsque tu cancel une review depuis le formulaire de revue, tu es redirigé vers le formulaire standard du document.
Sauf si contrainte technique, peux-tu rediriger l'utilisateur vers la section de la revue dans laquelle il se trouvait ?
Merci.

**Comment by thibault** [comment]
@Talengi Je ne peux pas rediriger vers la section précise parce que l'info n'est pas disponible au moment de l'annulation (à moins de construire une usine à gaz). Par contre, je peux [rediriger vers cette page](http://phase.clients.jouannic.fr/reviews/).

**Comment by Talengi** [comment]
@thibault OK faisons comme tu le proposes.
