### ISSUE TITLE
Problème avec le nommage des fichiers uploadés

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#137]
@thibault Peux-tu stp corriger, le nommage des fichiers à bougé.
Tu peux voir un exemple avec le doc FAC09001-CTR-000-MAI-SCH-6063
Le n'atif s'appelle : FAC09001-CTR-000-MAI-SCH-6063_03_OplF5V8.docx
Le PDF s'appelle : FAC09001-CTR-000-MAI-SCH-6063_03_cMNXGTR.pdf

**Comment by Talengi** [comment]
@thibault C'est le cas dans les 2 types de formulaires : standards et revue

**Comment by thibault** [comment]
Note : il s'agit d'un mécanisme inné de Django. Quand un fichier existe déjà, il ajoute un suffixe au nouveau fichier pour éviter d'écraser le précédent.

Normalement, dans phase, ce genre de conflit ne peux arriver car l'upload de nouveau fichier est pris en charge dans le formulaire de documents. Par contre, on va rencontrer le problème si on remet à zéro la base de données mais que les anciens fichiers n'ont pas été nettoyés, ce qui n'est pas un cas d'utilisation courant. C'est je pense que qui se passe ici.

À priori, il n'y a rien à faire car le problème n'apparaitra pas en production.
