### ISSUE TITLE
Bug avecd les docs cancelled et superseded lorsque tu es dans la barre de recherche

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#138]
@thibault Attention, gros bug lorsque tu coches la case "Show CLD/SPD docs" : les valeurs dans la facette "Status" passent du bon nombre à 0 partout de manière assez aléatoire j'ai l'impression.
Peux-tu regarder stp ?
Merci

**Comment by Talengi** [comment]
@thibault Lorsque tu selectionnes un des deux statuts dans la facette "Status" depuis la barre de recherche, toutes les autres valeurs passent à 0. Il faut les sélectionner pour afficher le bon nombre.

**Comment by thibault** [comment]
@Talengi C'est à priori un comportement normal. Chaque fois que les paramètres de recherches sont modifiés, toutes les facettes sont mises à jour.

Par exemple, si tu sélectionnes le statut « IFA », la facette « Unit » va être mise à jour pour montrer le nombre de documents ayant un statut IFA pour chaque valeur.

Maintenant, si tu sélectionnes un statut, toutes les autres valeurs de la même facette vont forcément avoir une valeur à zéro, puisque par définition on a filtré par un autre statut.

Traditionnellement, dans les recherches à facette, on supprime des facettes les paramètres qui ne renverraient pas de résultats (0).

On peut discuter de la meilleure façon de faire.

**Comment by Talengi** [comment]
@thibault On ne touche à rien, tout est normal et c'est très bien comme ça. Désolé !
