### ISSUE TITLE
URL et libellé des incoming transmittals

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#142]
@thibault Aujourd'hui, l'url se nomme http://phase.clients.jouannic.fr/transmittals/. Peux tu renommer en http://phase.clients.jouannic.fr/incomingtransmittals/ ?
La page se nomme "Transmittals", peux-tu la renommer en "Incoming transmittals" ?

Merci.

**Comment by thibault** [comment]
@Talengi Pour respecter les bonnes pratiques d'architecture des urls, je peux proposer l'url suivante : 

http://phase.clients.jouannic.fr/transmittals/incoming/

Est-ce que ça te conviendrait ?

**Comment by Talengi** [comment]
@thibault Je confirme, c'est ok.
