### ISSUE TITLE
Le Document Type "F&G" s'affiche mal

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#145]
@thibault Lorsque tu visualises le Document Type "F&G" au sein du Document Number, tu vois "FG".
Peux-tu corriger stp ?

**Comment by thibault** [comment]
@Talengi Le document number est utilisé en tant qu'identifiant du document dans l'url. Or, « & » est un caractère spécial et ne peut donc être utilisé.

En revanche, je peux ajouter un contrôle d'erreur pour empêcher un utilisateur de créer une valeur avec autre chose que des lettres. Est-ce que ça te paraît une solution envisageable ?

**Comment by Talengi** [comment]
@thibault On est obligés de gérer les caractères spéciaux dans les document types malheureusement. Est-ce que le plus simple n'est pas de modifier la gestion de l'URL afin que cela n'impacte pas les metadonnées dans Phase ?

**Comment by thibault** [comment]
@Talengi Je peux faire deux choses : 

 * J'enlève complètement le document number de l'url et je remplace par l'id du document, mais on y perd en fonctionnalité, en ergonomie et en sécurité.
 * Je gère deux champs en parallèle : le « vrai » document number qui pourra contenir des caractères spéciaux, et un champ « slug » qui sera uniquement utilisé dans l'url et autogénéré à partir du document number.

Dans le second cas, des questions se posent : doit-on laisser l'utilisateur saisir le slug lui même, ou l'autogénérer ? Si le document number est modifié, est-ce que le slug reste identique ou bien doit-il être modifié également.

**Comment by Talengi** [comment]
@thibault Je confirme le second cas.
Je pense que le slug doit être autogénéré. SI le document number est modifié alors le slug doit l'être aussi automatiquement.
Tu me dis si je ne réponds pas bien ou de si tu as besoin d'autres inputs.
