### ISSUE TITLE
Bouton download depuis interface des Ougoing Transmittals

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#148]
@thibault lorsque l'on sélectionne un transmittal et que l'on veut télécharger les fichiers, cela ne fonctionne pas.
C'est une bonne idée que tu as eu et j'aimerai que le comportement soit le suivant : 
- le clique sur download permet à l'utilisateur de télécharger le transmittal, plus le document de commentaires. Est-ce que l'on peut voir cela ?

**Comment by thibault** [comment]
@Talengi Juste pour confirmer, tu parles bien de l'action « download » sur la liste des documents ?

**Comment by thibault** [comment]
@Talengi Je ne peux pas adapter le téléchargement actuel, mais je peux créer une action de téléchargement dédiée aux transmittals.

Est-ce qu'on garde la fenêtre de configuration du download ? À priori, l'option « Pdf / native / both » n'a pas lieu d'être, mais est-ce qu'on garde l'option « latest / all revisions » ?

**Comment by Talengi** [comment]
@thibault Oui c'est le bouton download depuis la liste des transmittals.
Je propose que l'on adapte le bouton comme suit : 
- l'utiliseur peut choisir de télécharger le transmittal seul, les documents associés seuls ou les deux en même temps (both), la dernière (par défaut) ou toutes les révisions

**Comment by thibault** [comment]
J'ai avancé sur ce ticket, mais ce n'est pas terminé.

J'ai fait en sorte que la fonction qui empaquete les documents dans un fichier zip soit surchargeable par catégorie.

Le téléchargement contient maintenant le transmittal et les commentaires.

Pour le moment, le téléchargement n'est pas du tout configurable, il faut que je créé le formulaire spécifique.

Je n'ai pas fusionné la branche vue que la feature n'est pas complète.

La branche est sur mon dépôt github au cas ou.

**Comment by thibault** [comment]
@Talengi « l'utiliseur peut choisir de télécharger le transmittal seul, les documents associés seuls ou les deux en même temps (both) »

Ça a sans doute déjà été précisé, mais j'ai besoin d'un rafraichissement de mémoire. Lorsque l'utilisateur sélectionne « documents associés », que va-t-il télécharger ? Le fichier de commentaire associé à chaque document du transmittal, ou le fichier pdf ?

**Comment by Talengi** [comment]
@thibault Thibault, désolé mais je réalise que j'ai oublié de te préciser que le fichier de commentaires à télécharger est celui contenu dans le champ "Final comments".
Peux-tu stp me confirmer si c'est celui là que tu as pris en compte ou pas ? Si ça n'est pas le cas, peux-tu stp faire les modifs pour que ce soit le fichier de ce champ qui soit exporté ?
Merci.
