### ISSUE TITLE
Migration de OpenVZ à LXC

### ISSUE THREAD

**Issue by thibault** [Talengi/phase#150]
OpenVZ est une technologie mourante qui ne fonctionne pas sur les noyaux linux récents. LXC est une technologie alternative (à la base de Docker) équivalente supportée en standard sur les distributions linux récentes.

À l'occasion, il faudra fournir une doc d'installation à base de LXC.

**Comment by Talengi** [comment]
@thibault Ca veut dire que tu es capable de tout passer sur LXC dès à présent ou qu'il faudra le prévoir par le suite ?

**Comment by thibault** [comment]
@Talengi LXC est une technologie étonnament peu populaire et pour être honnête, je n'ai pas d'expérience avec. Mais le fonctionnement et les fonctionnalités sont équivalentes avec OpenVZ, et la plupart des projets commerciaux qui se basaient sur OpenVZ ont migré / sont en train de migrer vers LXC.

J'ai fait quelques tests pendant 20 minutes, et j'ai pu créer une machine virtuelle debian en quelques secondes sur ma machine qui tourne sous ubuntu. J'ai également vu des docs pour convertir des images openvz en images lxc (mais je n'ai pas testé).

Voici ce que je pourrais te proposer. Lundi (ou un autre jour de la semaine), j'essaye de réaliser une installation de Phase sur un container lxc, et je vois comment je peux transférer ça sur le serveur Sileo. Si ça marche, on se sera débarrassés d'Openvz et on n'aura pas besoin de downgrader le serveur de Sileo sur une version Debian qui ne sera peut-être plus maintenue très longtemps.

Si au bout d'une journée ça ne marche pas, on demande à Sileo de réinstaller leur serveur sous wheezy et on réalise l'installation sous OpenVZ.

Comme j'ai un intérêt personnel à tester la technologie et que je n'ai pas d'expérience avec, je te propose de ne pas te facturer la journée.

Je te laisse me dire si c'est compatible avec tes délais / objectifs.

**Comment by Talengi** [comment]
@thibault OK on fait cela. Mais tu me dis en cours de journée dès que tu sens un point bloquant ou une perte de temps qui serait préjudiciable au planning. L'idée est de pouvoir péreniser avec LXC, mais que l'on puisse aussi maximiser le fonctionnel sur le serveur so you start en attendant. 
Repasse sur les 2 tickets de bugs à présent stp et on voit LXC lundi.

Dans le même ordred d'idée, il faudra peut etre réfléchir à passer sur Ubuntu LTS, plutot que Debian au cas où non ?

**Comment by thibault** [comment]
@Talengi On fait comme ça. Pour ubuntu, je ne sais pas, j'ai toujours vu debian comme l'OS de référence pour les serveurs, mais c'est peut-être en train de changer. Je vais me renseigner.

**Comment by Talengi** [comment]
@providenz Laurent, est-ce que tu te sens de boucler ce ticket ? Passer le serveur Talengi sous Debian 8 et passer l'appli sous LXC afin que l'on utilise plus du tout OpenVZ ?
