### ISSUE TITLE
Related documents affiche tous les documents de toutes les orga/catégories

### ISSUE THREAD

**Issue by thibault** [Talengi/phase#155]
@thibault La fonction "Related documents" affiche les documents de toutes les orgas et catégories. C'est bien cela ? Si oui, il faudrait restreindre uniquement à la catégorie de l'organisations dans laquelle on est en train de créer/editer le document ?
On en parle.

**Comment by thibault** [comment]
@Talengi Matthieu, est-ce que tu peux confirmer que cette modif est à appliquer systématiquement pour toutes les catégories de documents sur l'ensemble de l'application ?

**Comment by thibault** [comment]
@Talengi Je viens de penser à un problème potentiel. Aujourd'hui, la section « related documents » est notamment utilisée par les transmittals pour lier les documents qui ont été importés / exportés.

Est-ce qu'il y a d'autres catégories ou les « related documents » peuvent pointer vers d'autres catégories ? Est-ce que ce sera à définir au coup par coup ?

**Comment by Talengi** [comment]
@thibault @providenz Oui je confirme. Merci.

**Comment by Talengi** [comment]
@thibault @providenz En effet, les transmittals peuvent avoir des liens vers des catégories différentes de la même organisation. Alors que les autres documents font des liens uniquement de la même catégorie.
Dans ce cas, faites ce ticket et on verra en janvier pour une fonctionalité de related documents spécifique aux transmittals, non ? Vous en pensez quoi ?

**Comment by thibault** [comment]
Ok, donc pour toutes les catégories sauf les transmittals, on limite les « related documents » à la catégorie courante.

**Comment by Talengi** [comment]
Oui merci !

**Comment by providenz** [comment]
Fixed by 647073c7a7ad74f76c6102250f137ec060ad4dd6
