### ISSUE TITLE
Gestion du champ Class et durée des revues

### ISSUE THREAD

**Issue by thibault** [Talengi/phase#156]
La durée de la revue (fixée au moment ou la revue est démarrée) est pour le moment fixe. Cette durée doit dépendre du champ « class » (en interne, « docclass »).

Les valeurs possibles pour le champ class et les durées correspondantes sont à définir en python et doivent être facilement surchargeables pour chaque catégorie.

Voir Talengi/sileodocs#5 pour l'historique.

**Comment by providenz** [comment]
Fix dans 2ce21953e9e62259a3088494925cf2c74f7b800a
