### ISSUE TITLE
Colonne update des favorites qui n'indique plus une mise à jour

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#166]
@providenz @thibault Pouvez-vous s'il vous plait regarder si l'indication d'une "update" sur un document mis comme favori fonctionne encore ou non ? J'ai créé une nouvelle révision sur un document qui j'avais en favoris et il n'y a pas d'indication qu'il a été updated.
Merci.

**Comment by Talengi** [comment]
Je précise que j'ai fait le test sur le serveur So You Start sur la base de test de Sileo.

**Comment by providenz** [comment]
Peux-tu décrire les étapes pour reproduire le problème.
J'ai essayé en local et sur le serveur, je ne vois pas le bug.

J'ai fait:
* mettre en favori un document
* éditer la dernière révision
* modifier un champ
* aller sur la liste des favoris
* l'icone de mise à jour en point d’exclamation apparait bien dans la ligne du document modifié

**Comment by providenz** [comment]
Bug reproduit, ça dépend des champs  en fait.

**Comment by Talengi** [comment]
@providenz Je n'ai pas trouvé de bug. Reteste vite fait et si tu ne vois pas de problème et que les tests automatisés sont OK, alors tu peux fermer ce ticket.

**Comment by providenz** [comment]
@Talengi le fonctionnement est conforme
