### ISSUE TITLE
Line break in document title breaks csv export

### ISSUE THREAD

**Issue by providenz** [Talengi/phase#169]
The document title field is a TextField and accepts multiline text.
However during exports, the serialization process writes csv without getting rid of this carriage returns thus producing broken csv files.

How to reproduce:
* add or edit a document tile by adding a line break
* export the document list it belongs to
* download and open the csv file 

Related code is in exports/formatters.py

**Comment by providenz** [comment]
Closed by fb970f062932c642a05a6711a4f371fa7a1aa320

**Comment by Talengi** [comment]
@providenz Je viens de faire un essai d'export avec un titre sur deux lignes : on est bien d'accords que l'export en CSV ne va pas tenir compte du titre qui est sur 2 lignes dans Phase et va présenter un titre sur une seule ligne ? 
Si c'est le cas, aucun problème pour moi, je veux juste vérifier que c'est le comportement attendu.
Merci !

**Comment by providenz** [comment]
@Talengi oui c'est le cas
