### ISSUE TITLE
Gestion des dates Actual dans le formulaire standard de documents

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#172]
@providenz 

Le formulaire standard de document comporte une section "Schedule" avec différentes dates qui concernent le planning du cycle de vie du document (on indique dans les colonnes "Planned" et "Forecast" quand on pense émettre le document pour chacun des statuts).
La colonne Actual n'est à ce jour pas gérée. Son but est d'indiquer quand a réellement été émis un document.
Pourrais-tu faire le développement nécessaire pour que la colonne Actual soit automatiquement remplie par Phase pour chacun des statuts ? La règle est la suivante : 
- Le doc controller créé un document dans Phase
- Il indique un statut (IDC, IFR, AFC, ASB, etc.)
- Phase va automatiquement reprendre la date du champ "Created on" et l'indiquer automatiquement dans la colonne "Actual" de la section "Schedule", pour la ligne correspondant au statut indiqué par le doc controller
- Si jamais un document a plusieurs révisions au même statut, c'est la première date qui importe, la dates suivantes ne seront pas renseignées dans la section "Schedule"

Ca te parait clair ?

**Comment by thibault** [comment]
@Talengi Je résume pour vérifier que j'ai bien compris.

Je créé une nouvelle révision pour un document, et je lui donne un statut « IFI ». La date du jour est alors automatiquement renseignée pour le champ « IFI > Actual ». C'est bien ça ?

Quelques questions : 
 - Que se passe-t-il si je change le status d'une révision existante ? Est-ce qu'on doit le prendre en compte dans la section schedule ?
 - Est-ce que le DC peut toujours renseigner la date manuellement ?

**Comment by thibault** [comment]
Réponses (vu au téléphone) :

- Quand le statut d'une révision est changé, la section « schedule » doit être mise à jour en conséquence.
- Le renseignement des dates « actual » n'est plus gérable manuellement, tout est automatique.
