### ISSUE TITLE
Exporter les dates de la section "Schedule" dans l'export CSV

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#173]
@providenz 

La section "Schedule" présente dans le formulaire standard de document, n'est à ce jour pas exportée dans les exports CSV.
Peux-tu s'il te plait faire le nécessaire afin que l'on retrouve toutes les dates des trois colonnes (Planned, Forecast, Actual) pour tous les statuts dans le CSV ?
Il faudrait tout placer en dernière position dans le CSV.
L'ordre de présentation est le suivant : 
- Toutes les dates des statuts "Planned"
- Puis toutes les dates des statuts "Forecast"
- Puis toutes les dates des statuts "Actual"

Est-il possible d'avoir un en tête de colonne qui s'écrive comme suit : <trigramme du statut> <Planned>. Par exemple : "IFR Planned", ou "ASB Forecast", ou "IDC Actual"

Ca te parait clair ? C'est gérable ?

**Comment by thibault** [comment]
@Talengi La liste des champs à exporter se défini au cas par cas pour chaque catégorie de documents. À part pour les ContractorDeliverables, y a-t-il d'autres catégories à prendre en compte ? EPC2 ? Sileo ?
