### ISSUE TITLE
Affichage de la valeur du champ Review step

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#176]
@thibault Sur le serveur So You Start, je vois que la valeur contenue dans le champ "Review step" commence sans majuscule. Peux-tu stp faire les modifs nécessaires afin que toutes les valeurs s'écrivent avec majuscule : 
- Reviewer et pas reviewer
- Leader et pas leader
- Approver et pas approver

Peux-tu vérifier que partout dans l'application il y aura bien la majuscule et que cela sera bien dispo sur tous les déploiements (sur ton serveur comme sur le serveur so you start ou un autre) ?

**Comment by thibault** [comment]
@Talengi Peux-tu me préciser ou tu vois cet affichage, car dans la liste des revues, l'affichage me semble bien en majuscule ?

**Comment by Talengi** [comment]
@thibault Si je vais dans le formulaire de revue d'un document under review, je vois cela. Effectivement, dans le formulaire standard, la valeur a bien une majuscule. C'est comme si il y avait 2 types de valeurs différentes.
