### ISSUE TITLE
Cases à cocher mal alignées dans barre de recherche

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#182]
@thibault Je suis sur Mac, sous Safari et les cases à cocher "Show CLD/SPD docs" et "Ready for outgoing TRS" sont alignées à gauche sur la ligne du dessous au lieu d'être centrées.
Tu reproduis ? Si oui, peux-tu stp rectifier ?

**Comment by Talengi** [comment]
@thibault Autre chose : si tu décoches la case, puis la recouches, elle bouge. Tu reproduis ?

**Comment by thibault** [comment]
J'ai corrigé l'affichage, et tout passe maintenant sous Chrome. Tout est-il ok sous Safari ?

**Comment by Talengi** [comment]
@thibault C'est bon pour Chrome et Firefox sous Windows. e ferai en sorte de tester sous Safari.

**Comment by Talengi** [comment]
@thibault Le bug persiste sous Safari, mais ça n'est pas critique pour le moment.
