### ISSUE TITLE
Barre de recherche à fermer manuellement lorsque tu affiches les documents ready for outgoing transmittals

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#183]
@thibault On en a déjà parlé je crois : lorsque tu veux afficher les docs "ready for outgoing transmittals", tu descends en bas de la barre de recherche pour cocher la case. Du coup il faut ensuite remonter en haut de la barre de recherche pour cliquer sur "Close" pour ne plus faire apparaitre la barre de recherche.
Ca n'est pas bloquant, mais pas agréable au quotidien dans la cadre d'une utilisation intensive.
Ne peut-on pas trouver un autre moyen pour la faire disparaitre ? Un clic ailleurs dans l'interface et a barre disparait (comme on voit cela dans certaines applis) ? Ou alors placer le filtre "ready for outgoing trs" ailleurs ?

**Comment by thibault** [comment]
J'ai fait en sorte que les colonnes se ferment via la touche « echap ». Je n'ai pas associé le clic en dehors à une fermeture de la barre latérale, parce qu'il est possible d'interagir avec la liste des documents tout en gardant le moteur de recherche affiché, et il me semble que c'est un fonctionnement utile.

**Comment by Talengi** [comment]
@thibault J'imagine que tu n'as pas encore livré cela car je ne vois pas la différence de mon côté ?
