### ISSUE TITLE
Réouverture de la barre de recherche après avoir créé le outgoing transmittal 

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#184]
@thibault Lorsque tu veux créer un outgoing transmittal : 
- tu ouvres la barre de recherche
- tu descends en bas de la barre
- tu coches la case "ready for outgoing trs"
- tu remontes la barre et tu cliques sur "close"
- tu créés ton outgoing transmittal"
- la pop up s'ouvre
- tu valides
- la barre de recherche réapparait

est-ce que tu peux stp annuler ce dernier comportement : la barre de recherche n'a pas besoin de réapparaitre.
Merci.

**Comment by thibault** [comment]
J'utilise maintenant un cookie pour gérer l'affichage du formulaire. Si le formulaire est ouvert, il restera ouvert même en rechargeant la page ou en navigant ailleurs sur l'application avant de revenir à la liste de documents.

Même chose pour l'état « fermé ».
