### ISSUE TITLE
Le champ "Search all columns" ne cherche pas dans toutes les colonnes

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#189]
@thibault Dans la barre de recherche, lorsque tu indiques le nom d'un utilisateur dans le champ "Search all columns" pour faire une recherche, il n'y a aucun résultat qui sort.
Ca n'est pas un problème grave puisque tu peux filtrer par Leader et Approver, mais ca n'est pas le résultat attendu par un utilisateur.
Peux-tu regarder cela stp ?

**Comment by thibault** [comment]
@Talengi J'ai modifié pour que la recherche se fasse sur le contenu de toutes les colonnes. Je te recommande de faire quelques tests sur les moteurs de recherche pour bien valider que tout fonctionne encore comme prévu, car c'est une modif qui impacte du code assez ancien.

**Comment by Talengi** [comment]
@thibault A priori, le seul problème que je vois toujours est au niveau de la recherche dans la colonne "Under review" si l'on tape Yes ou No dans le champ de recherche, ça ne marche pas.
Je rouvre donc ce ticket pour la forme, mais il n'y a aucun point bloquant et pas d'urgence.

**Comment by thibault** [comment]
@Talengi Ça va commencer à être délicat, parce que « Yes » et « No » ne sont pas vraiment des valeurs présentes dans la base ou ES, ce ne sont que des labels utilisés par l'interface. Les rendre cherchables va demander de se creuser un peu la tête, il faut voir si ça en vaut bien la peine.

**Comment by Talengi** [comment]
@thibault Comme discuté, ce n'est pas du tout bloquant, on oublie et je ferme cette carte.
