### ISSUE TITLE
Impossible de supprimer un document après en avoir changé le numéro

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#190]
@thibault Si tu modifies le document number d'un document existant, celui-ci devient inaccessible. J'imagine qu'informatiquement, tu as mis les protection nécessaires pour que l'on ne puisse pas faire n'importe quoi. 
Le problème ici est que si l'on sauvegarde une modif sur le document number, le document devient inaccessible. Il reste listé dans l'orga/catégorie concernée, mais on ne peut plus rien en faire.

Il faudrait donc soit : 
- Empêcher totalement la modification sur un document number et indiquer au doc controller qu'il ne peut pas modifier le doc number et qu'il doit supprimer le doc et en créer un autre
- Avoir la possibilité de supprimer un (ou plusieurs) document depuis le bouton "Actions" de la liste de documents

Qu'est-ce qui serait le plus simple et rapide ? Ma préférence va à la première solution car pouvoir supprimer plusieurs docs d'un coup me semble dangereux.

**Comment by thibault** [comment]
@Talengi En local, le renommage de document fonctionne bien, les redirections se font, et l'indexation est mise à jour. Le document est correctement supprimé.

C'est peut-être un problème lié aux différents transferts de données pour installer Sileo. Il faudrait que je teste sur leur recette, quand j'aurai accès au vpn.

Pour la suppression de documents en bloc, c'est une fonctionnalité à part entière. On peut imaginer une liste de documents dans l'admin et une action de suppression qui s'effectuerait sur plusieurs documents). Veux-tu que je créé la carte dans Trello ?

**Comment by Talengi** [comment]
@thibault Oui stp, merci.

**Comment by thibault** [comment]
@Talengi Après tests, il y a effectivement un problème avec l'indexation des documents quand on renomme un document avant de le supprimer. Je vais regarder ça, donc.
