### ISSUE TITLE
Barre de recherche des Outgoing Transmittals

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#192]
@thibault Peux-tu s'il te plait faire les modifications suivantes dans la barre de recherche des Outgoing Transmittals : 
- Enlever "Contract Number"
- Ajouter "Originator"
- Ajouter "Recipient"
- Renommer "Ack of receipt" en "Acknowledgment of receipt"

Merci !

**Comment by thibault** [comment]
@Talengi En l'état actuel des choses, le champ « originator » n'est pas une liste prédéfinie, c'est une simple séquence de caractères. Ce type de champ ne peut être utilisé en tant que filtre sans développements supplémentaires assez lourd. On en rediscute si tu veux.

**Comment by Talengi** [comment]
@thibault OK tant que l'on peut taper une partie du numéro du transmittal dans le champ "search all columns", cela permet de filtrer par originator ou recipient de manière détourner, donc je pense que cela répond au problème sans nécessiter de nouveaux devs. Donc gère les 2 autres bullet points et oublie originator et recipient.
Merci !
