### ISSUE TITLE
Retour à la liste des favoris après avoir consulté un document marqué comme favori

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#195]
@thibault Si tu consultes un document depuis ta liste de favoris, et qu'ensuite dans le formulare, tu  cliques sur "Close", tu es redirigé vers la liste de documents de la catégorie concernée.
Pour moi, c'est perturbant et il faudrait modifier ce comportement. 
Peux-tu modifier afin qu'un clic sur le bouton "Close" fasse revenir le document sur la liste des favoris ?

**Comment by thibault** [comment]
@Talengi Alors le problème, c'est que ce fameux bouton « close » n'est qu'un bête lien vers la liste des documents. Peut importe d'où l'on vient, chaque page est indépendante. Pour avoir un bouton qui retienne l'origine, il va falloir que je développe une usine à gaz.

C'est gérable, mais ça va être très compliqué pour pas grand chose.

Peut-être qu'on peut lever l'ambiguité en renommant le bouton en « retour à la liste de docs ». Pour retourner aux favoris, le bouton « back » du navigateur fonctionne comme voulu, non ? Est-ce que ça réglerait le problème ?

**Comment by Talengi** [comment]
@thibault On utiliseras le bouton back du navigateur et je ferme le ticket, ne perdons pas de temps. Merci !
