### ISSUE TITLE
Revenir à la liste des documents à revoir lorsque l'on quitte le formulaire de revue d'un doc

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#196]
Lorsque je consulte le formulaire de revue d'un document et que je clique sur Close sans avoir traité la revue, je ne reviens pas sur la liste des des documents à traiter dans laquelle je me situai juste avant (soit en tant que reviewer, ou leader ou approver), mais sur l'écran de la section "Review", qui liste les priorités et les étapes de la revue.
Il faudrait que lorsque je clique sur "Close", je revienne à la liste de l'étape du document.

**Comment by thibault** [comment]
@Talengi Même problème que 196. En fait, on ne peut pas afficher un bouton qui se comporte à moitié comme un lien et à moitié comme le bouton « retour » du navigateur. Ce bouton est-il vraiment utile ? Ne peut-on le supprimer tout bêtement pour supprimer les ambiguités ?

**Comment by Talengi** [comment]
@thibault Je pense que ne pas avoir de bouton du tout est perturbant pour l'utilisateur et qu'en l'état du temps que l'on peut passer là dessus, je ferme le ticket et on indique aux utilisateurs qu'ils cliquent sur back du navigateur pour revenir à la liste de l'étape de la revue.
Je ferme donc ce ticket.
