### ISSUE TITLE
Export reste en processing et non accessible sans F5

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#197]
On retrouve le même "bug" que l'on avait en décembre : lorsque l'on lance un export CSV, la nouvelle ligne ajoutée, reste au statut "Processing" et le lien hypertexte n'est pas accessible. Il faut rafraichir la page pour y avoir accès.
Il faudrait corriger afin que le statut soit "Done" et que le lien hypertexte soit directement disponible.

**Comment by thibault** [comment]
@Talengi Le problème est que l'export est une tâche qui tourne en arrière plan, lancée par Celery. Tant que l'export n'est pas terminé, on ne peut pas permettre le téléchargement.

On pourrait sans doute bloquer l'utilisateur et afficher une barre de chargement, mais c'est quand même dommage, d'autant que s'il y a beaucoup de documents, ça peut prendre pas mal de temps.

On peut peut-être s'en sortir en affichant un message d'information au bon endroit ?

**Comment by Talengi** [comment]
@thibault @providenz 
Lorsque Laurent a travaillé sur le sujet en décembre, le problème de rafraichir la page a été corrigé. On avait plus besoin de le faire à la main, le statut était done et le lien hypertxte présent pour ouvrir le CSV donc que l'on était basculé sur la section exports. Donc il a du se repasser quelque chose entre temps.
Peux-être peux-tu voir avec Laurent comme il a procédé ?

Sinon je propose les alternatives suivantes : 
- Soit on a effectivement une barre de défilement et on continue de rediriger automatiquement l'utilisateur vers la section Exports, une fois le CSV généré. Dans ce cas, on est surs qu'il aura accès au CSV. La contrepartie est que l'utilisateur doit attendre le temps que le process soit terminé. Si c'est 5 à 10  secondes, cela ne présente aucun problème. SI c'est 30 secondes à 1mn, cela me gène.
- Soit on lance la tâche de fond comme aujourd'hui, mais on laisse l'utilisateur sur la liste de documents depuis laquelle il a lancé l'export. Lorsque l'export est prêt, l'icone de notification devient rouge et indique que l'export est prêt. Il peut ainsi aller chercher son CSV qui sera en statut "Done" et accessible. Cette seconde méthode me parait pas mal : l'utilisateur n'est pas bloqué, peut faire autre chose et l'appli lui indique quand son export est prêt.

Tu en penses quoi ?

**Comment by thibault** [comment]
@Talengi Ok, je ne savais pas qu'il y avait eu un dev spécifique sur le sujet. Je vais regarder ça, du coup.

**Comment by thibault** [comment]
@Talengi Après investigation, il me semble que le problème corrigé par Laurent était d'une autre nature : l'export csv ne fonctionnait tout simplement pas, mais l'aspect « tâche de fond » de la fonctionnalité n'a pas été touché.

À noter que dans certains cas, l'export se fait tellement vite que le lien est tout de suite disponible. Mais pas tout le temps.

Je pense que la meilleure solution est la deuxième. C'est la plus logique et intuitive, et la plus facile à implémenter.
