### ISSUE TITLE
Modification des champs du formulaire d'outgoing transmittal

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#201]
Dans le formulaire d'outgoing transmittal, les champs suivants sont à retirer : 
- Sequential number
- Revision date
- Received date

Le champ suivant est à ajouter : 
- Acknowledgement of receipt (Yes / No)

Les champs "Originator" et "Recipient" doivent présenter les valeurs comme les champs "Originator" des documents, par exemple : "CLI - Client"

**Comment by thibault** [comment]
@Talengi Quelques questions sur ce ticket.

Le champ « received date » est un champ commun obligatoire à toutes les révisions dans Phase. Le supprimer va demander quelques refactorings. Ça vaut le coup ?

Le champ « originator » n'est pas une liste de sélection, c'est un simple champ texte. Pareil, il va falloir quelques refactorings pour obtenir ce que tu veux. Je le fais ?

**Comment by Talengi** [comment]
@thibault Je confirme pour les deux, même si cela te demande du temps.
Tu me diras si jamais c'est plus compliqué que ce que tu penses et que tu bloques.

**Comment by Talengi** [comment]
@providenz Pas sur que ce ticket ait été traité ou finalisé. La received date est toujours dans le formulaire.

**Comment by providenz** [comment]
Champ received_date retiré des OutgoingTransmittals e8742093110c7c41a25be10462514bd5ce73e8ae
