### ISSUE TITLE
Insertion des logos ETI et Sileo sur les outgoing transmittals

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#202]
Nous allons devoir gérer 2 types d'outgoing translmittals : ceux relatifs aux projets ETI et ceux relatifs aux projets Sileo.
Il faut donc que chacun ait son logo qui apparaisse en particulier.
Peut-on commencer par insérer le logo d'ETI en haut à gauche du transmittal ?

**Comment by thibault** [comment]
@Talengi Pour l'instant, la fonctionalité qui consiste à insérer un logo n'est pas dévelopée (les tests réalisés en ce sens n'étaient que des prototypes écrits rapidement).

Peut-on gérer cette feature dans Trello ? Il faut décider comment on le gère, est-ce qu'on laisse le client uploader et gérer son logo, à quel niveau, etc.

**Comment by Talengi** [comment]
@thibault Ok pour mettre cela dans Trello. Cela consiste uniquement à définir un modèle de transmittal avec un logo spécifique et c'est tout. Le client ne fait rien à son niveau.

**Comment by Talengi** [comment]
@providenz Je dois joindre le template à jour d'outgoing transmittal.

**Comment by providenz** [comment]
Feature dans 49ae536c0a1e3e6224c5e5d478c83f53095f6439
