### ISSUE TITLE
Permissions sur les revues

### ISSUE THREAD

**Issue by thibault** [Talengi/phase#207]
Lorsque j'accède à une revue avec une mauvaise url (e.g avec un doc number qui n'existe pas ou n'est pas en revue), j'ai une page d'erreur au lieu d'un message d'avertissement plus propre.

**Comment by Talengi** [comment]
@thibault Tu as moyen de régler cela histoire que tous les bugs aient disparus du github ou c'est un peu long et pas si critique cela ?
