### ISSUE TITLE
Bug sur téléchargement des outgoing transmittals

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#208]
@thibault Comme discuté vendredi, j'ai eu le bug suivant lorsque j'essayais de télécharger des transmittals : j'obtiens bien l'archive, avec le transmittal, mais pas le final comment.
Peux-tu regarder ?

**Comment by thibault** [comment]
@Talengi Peux tu me donner des détails, notamment les documents que tu as essayé de télécharger, et sur quelle url ?

**Comment by Talengi** [comment]
@thibault Le cas se présente avec le transmittal 15172-ETI-CTR-TRS-00002, qui est à l'URL suivante http://phase.talengi.com/eti/outgoing-transmittals/15172-ETI-CTR-TRS-00002/

Je télécharge depuis l'URL suivante : http://phase.talengi.com/eti/outgoing-transmittals/
