### ISSUE TITLE
Impossible de fermer la revue en tant que Leader sur le doc VX-512-J42-0001

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#211]
@thibault Je ne sais pas si c'est un problème de synchro : je suis connecté en tant que Leader sur le doc VX-512-J42-0001. J'ai fermé l'étape des reviewers, puis j'ai ajouté un fichier de commentaires et indiqué un return code. J'ai cliqué sur "finish review" et là je suis tombé sur une page "This is not the page you were looking for." avec l'URL suivante : http://phase.talengi.com/reviews/VX-512-J42-0001/fieldset-your-comments/#fieldset-your-comments

Peux-tu regarder ?

**Comment by thibault** [comment]
@Talengi Pour corriger ce bug, j'ai du modifier des fichiers js, il faut donc s'assurer que le cache est bien vidé pour vérifier la correction.

Le problème était du au fait de cliquer sur un lien dans le menu de la review, avant de soumettre le formulaire.

**Comment by Talengi** [comment]
@thibault Ah oui, là quand même c'est très vicieux ! Je te laisse fermer lorsque c'est bouclé.

**Comment by Talengi** [comment]
@thibault J'ai rien dit, tu as déjà fermé, donc on est bons.
