### ISSUE TITLE
Comment ajouter un "Recipient" pour les outgoing transmittals

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#212]
@thibault J'essaye d'ajouter un recipient pour les outgoing transmittals, mais je n'y arrive pas.
Dans l'admin, j'ai ajouté "BW Offshore", mais je ne le vois pas apparaitre lorsque je veux crééer un outgoing transmittal dans Sileo > 15005 — PECAN HUB FPSO
Pourquoi est-ce que cela n'est pas pris en compte ?

**Comment by thibault** [comment]
@Talengi Pour créer un recipient, il faut aller dans l'admin.

1) Dans « entities », créer une nouvelle entrée.
2) Il faut ensuite modifier la catégorie dans laquelle tu veux ajouter ton recipient (ici : Pecan Hub FPSO) et assigner le recpient dans le champ « third parties » (tout en bas).

Et ça devrait fonctionner. J'ai fait le test sur la recette.
