### ISSUE TITLE
Bookmarks spécifiques à chaque liste de documents ?

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#215]
Pouvez-vous s'il vous plait me confirmer que les bookmarks sont bien spécifiques à chaque liste de documents ?
Merci.

**Comment by thibault** [comment]
@Talengi Oui, les bookmarks sont spécifiques à la catégorie de document dans laquelle tu te trouves. Si tu créé un bookmark dans la catégorie A, il ne sera pas visible depuis la catégorie B.
