### ISSUE TITLE
Séquance d'affichage lors de l'ajout d'un nouveau reviewer

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#222]
@providenz @thibault 

Lorsque j'ajoute un nouveau reviewer à une distribution en cours, l'affichage de la liste distribution ne se fait plus en séquance : c'est le ernier ajouté qui est listé le plus en bas, et non la personne de l'étape la plus haute de la revue (leader ou approver). 
Il faudrait conserver l'étape la plus haute comme derniere ligne affichée.
Pouvez-vous voir cela ? Merci.

**Comment by providenz** [comment]
Closed by 315331e4b3d209d46a62f0171ff09b3008e85d9a
