### ISSUE TITLE
Bug lors de la modification d'une liste de distribution

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#223]
@providenz @thibault 

Après avoir modifié une liste de distribution, et suite au ticket #222, je constate d'autres problèmes à corriger : 
- Si je supprime le nom que j'avais ajouté et que je sauvegarde, l'affichage est inversé et c'est le Leader qui est listé avant le reviewer
- Dans les reviewers, j'avais indiqué 2 personnes. Il me semble avoir supprimé un nom, sauvegardé, mais Phase a supprimé l'autre nom. Est-ce que vous reproduisez ?
- Lorsque j'ai remodifié le nom du reviewer et n'en ai conservé qu'un, je vois que Phase indique l'icone de la date de traitement, alors que rien ne devrait apparaitre.

Tout cela se passe sur le document GX-502-V3I-0001, dans     ETI > 15215 — PIL & BUE

J'ai laissé en l'état et vous pouvez regarder.

**Comment by providenz** [comment]
Pour les 2 premiers points:

* L'ordre des intervenants a été corrigé dans la #222
* le pb est confirmé lors de la suppression d'un reviewer. Ça semble venir du widget frontend (js).

**Comment by providenz** [comment]
Point 1 & 2 réglés par 429348a6ef27ee60c4f7dcffb9066cbea548638b
@Talengi Le point 3 est complètement différent, je propose d'ouvrir un autre ticket spécifique, j'aurais besoin de clarification sur le processus métier attendu.
