### ISSUE TITLE
STart review with remarks depuis la liste de documents ne marche pas

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#224]
@thibault @providenz J'ai démarré une review en ajoutant une remarque depuis la liste de document dans ETI > 15215 — PIL & BUE, sur le doc GX-502-3668-ABS-0123 et la remarque n'a pas été prise en compte.
Pouvez-vous regarder ?

**Comment by Talengi** [comment]
Les remarques peuvent être enregistrées en cours de revue, mais les mentions ne fonctionnent plus.

**Comment by providenz** [comment]
Fix by a19bd4a1a73dc4f76e0665266cba976c61f65f04
