### ISSUE TITLE
Collisions de clés de documents

### ISSUE THREAD

**Issue by thibault** [Talengi/phase#227]
Il faudrait faire un point sur la génération de clés de documents, car j'ai un doute.

Aujourd'hui, quand on créé un document, le document_number est généré automatiquement.

La clé est unique au niveau de la catégorie, ce qui est logique, et la vérification est bien faite dans la validation du formulaire.

Toutefois, il y a aussi une unicité au niveau global, et cette contraine n'est pas testée. Par exemple, si je créé un document « TOTO » dans une catégorie A, et j'essaye de créer un document « TOTO » dans une catégorie B, j'ai un message d'erreur mais ne peut pas créer de document.

Par ailleurs, quand on créé un transmittal, la clé est générée automatiquement, et en cas de conflit avec un document existant, il y aura probablement une erreur.

**Comment by Talengi** [comment]
@thibault @providenz C'est une bonne question et je dirai que l'important est l'unicité au sein d'une même catégorie, mais en fonction de la manière dont un client veut organiser les docs dans Phase, cela a ses limites. Il faut donc à mon sens une vérif sur l'ensemble de l'application et on ne peut donc pas avoir 2 fois TOTO dans Phase, quelle que soit l'orga/catégorie.

Ca répond au ticket ?

**Comment by thibault** [comment]
@Talengi Est-ce que cela ne va pas poser problème, par exemple si j'ai les transmittal XXX-0001, XXX-0002, XXX-0003 et XXX-0005 parce que le XXX-0004 est un document existant dans une autre catégorie ?

**Comment by Talengi** [comment]
@thibault @providenz Il faut que dans la chaine de caractère, il y ait au moins 1 élément spécifique. A minima, un projet a un numéro unique qui est souvent généré chez les entreprises dans SAP ou un autre ERP afin de gérer tous les aspects budgets. Cet identifiant projet est unique et peut rentrer dans le numéro de doc, donc on va y arriver ainsi.

**Comment by thibault** [comment]
@Talengi On peut donc partir du principe que le cas n'arrivera jamais et on ferme le ticket ?
