### ISSUE TITLE
Import system can create new revisions for documents under review

### ISSUE THREAD

**Issue by thibault** [Talengi/phase#23]
One cannot create a new revision for a document under review.

The import module won't raise an error in that case, though, which might lead to an inconsistent state.

**Comment by thibault** [comment]
@Talengi Il y a maintenant deux fonctionalités d'import.

La première développée il y a quelques mois, qui permet d'uploader et d'importer un fichier csv dans l'interface Web.

Le seconde, récente, permettant d'importer des transmittals complet.

Question : la première version est-elle toujours d'actualité, ou est-elle rendue obsolète ?

**Comment by Talengi** [comment]
@thibault Désolé, je tarde à te répondre. 
Il faut bien conserver les 2 méthodes. En fait, j'avais mal compris un truc et je pense que cela va occasioner du travail...
1er import développé il y a quelques mois : c'est celui-ci que l'on doit utiliser pour l'import de masse, comme on l'a fait sur le dernier sprint.
Le 2ème import concerne les transmittals : on retravaillera cet import par la suite. En général un transmittal ne contient que entre 1 et 100 documents maximum.

Tu as besoin que l'on en parle par téléphone ?

**Comment by thibault** [comment]
@Talengi ? Je n'ai pas compris ta remarque. L'import d'il y a quelques mois n'a pas été touché depuis. Lors des derniers sprints, c'est un tout nouveau système d'import qui a été développé, et qui fonctionne par dépôt de fichier sur un ftp. Je crois qu'il faudrait clarifier ça au téléphone, car j'ai peur qu'il y ait quid pro quo.

**Comment by Talengi** [comment]
@thibault On triate les questions d'import soit la semaine prochaine, soit au cours de la prochaine itération.

**Comment by thibault** [comment]
Voici le code du test à implémenter dans `imports/tests/test_models.py` :


    def test_import_revision_document_under_review(self):
        """Documents under review cannot be revised"""
        doc = DocumentFactory(
            document_key='toto',
            category=self.category,
            revision={
                'reviewers': [self.user],
                'leader': self.user,
                'approver': self.user,
            }
        )
        doc.latest_revision.start_review()
        self.assertTrue(doc.latest_revision.is_under_review())

        data = {
            'document_key': 'toto',
            'title': 'New title',
            'status': 'IDC',
            'docclass': '1',
            'created_on': '2015-10-10',
            'received_date': '2015-10-10',
        }
        imp = Import(batch=self.batch, data=data)
        imp.do_import(line=2)
        imp.save()

        self.assertEqual(imp.status, 'error')
