### ISSUE TITLE
Notifications export CSV

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#230]
@thibault @providenz Pour vérification du code et test.
Lorsque je lance un export CSV, j'ai bien la notif indiquant que le CSV est processing, mais je ne vois pas la notif disant que c'est prêt. Est-ce bien du au fait qu'il faut recharger la page ?
Aujourd'hui, vu que l'on a des petites listes de docs, cela va très vite à faire. Est-ce que l'on a moyen de savoir ce que cela demanderait comme temps sur une liste de 4000 docs, multiplié par N révisions ?

**Comment by providenz** [comment]
4000 docs générés sur le serveur, 7 à 12 révisions par doc -> quelques secondes (- de 10) pour l'export csv
