### ISSUE TITLE
Format de date de la section outgoing transmittal du formulaire standard de document

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#237]
@providenz Lorsque l'on créé un outgoing transmittal, le format présenté dans le formulaire standard du document associé est MM/JJ/AAAA, ce qui n'est pas cohérent avec le reste des champs date du formulaire ou de Phase.
Peux-tu stp remettre le format en AAAA/MM/JJ ?
Merci.

**Comment by thibault** [comment]
@Talengi Peux-tu préciser sur quels champs tu constates ce phénomène ? Chez moi, tous les champs apparaissent avec le format standard.

**Comment by Talengi** [comment]
@thibault Le champ se trouve dans le formulaire standard de doc, dans la section outgoing transmittal. C'est le champ "outgoing transmittal" : lorsqu'un transmittal est assicé à un doc, un lien hypertexte apparait présentant le numéro du transmittal et entre parenthèses, on trouve la date dans ce format. Tu peux voir l'exemple sur : http://phase.talengi.com/eti/pil-bue/GX503-ABC-0789/

**Comment by thibault** [comment]
@Talengi Tous les champs date sur la page sont en format "Y-m-d", donc c'est ce que j'ai utilisé, mais j'ai aussi fait en sorte d'utiliser les fonctionalités d'internationalisation de Django, donc c'est facilement changeable. Tu me dira si ça te convient.

**Comment by thibault** [comment]
Petit hiatus de ma part, le ticket a déjà été corrigé par Laurent.
