### ISSUE TITLE
Permettre de créer des outgoing transmittals depuis l'organisation Sileo

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#239]
@providenz Peux-tu s'il te plait faire les réglages nécessaires à la création d'outgoing transmittals depuis l'organisation Sileo ?
Il faut je pense : 
- créer une nouvelle catégorie de doc
- que la "destination category" de l'organisation Sileo soit disponible (on ne voit que "ETI" pour le moment, lorsque l'on veut créer un transmittal depuis une catégorie de l'orga Sileo

On en parle si tu veux.

**Comment by thibault** [comment]
@Talengi Sur quelle plateforme / env faut-il effecture ce changement ?

**Comment by Talengi** [comment]
@thibault Mets ça en place demain (à partir de 12h) sur le le serveur talengi et sur la VM de test de sileo.
