### ISSUE TITLE
Permettre de faire des imports de documents

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#240]
@providenz Peux-tu stp faire fonctionner la fonctionnalité d'import de documents sur le serveur de test ?

**Comment by thibault** [comment]
@Talengi Juste pour être certain, tu parles bien de la recette, et pas du serveur de test de Sileo ?

**Comment by Talengi** [comment]
@thibault à moi d'être plus précis à présent, désolé :)
Mets les mécanismes en place pour que cela fonctionne sur le serveur talengi et sur la VM de test de Sileo.
Il faut que l'on établisse un CSV standard qui nous permette de faire les imports. Je suppose que tu auras besoin de mes inputs ?

**Comment by Talengi** [comment]
@providenz Peux-tu regarder cela ou est-ce compliqué ?

**Comment by Talengi** [comment]
@providenz 
- Adapter le CSV aux 2 modèles de données (et donc avoir 2 CSV différents)
- Depuis le même CSV, en fonction des colonnes remplies, permettre d'importer de créer des documents dans Phase via les colonnes communes à tous les docs, comme permettre de créer des révisions lorsque les colonnes concernées sont remplies. Chaque révision d'un document est listée l'une sous l'autre.

**Comment by providenz** [comment]
Dans 1ed6b1a630a0e70e63de8a68b8af34dd3214b399
