### ISSUE TITLE
Finalisation des outgoing transmittals dans Phase

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#245]
@thibault @providenz 
Je joins à ce mail les logos de Sileo et ETI.
Il faut donc avoir 2 outgoings transmittals dans Phase : 1 pour ETI et 1 pour Sileo. Chaque transmittal portera uniquement le logo de la société concernée.

Concernant le champ "Sender" sur le PDF, il faut indiquer la même adresse pour les 2 sociétés, mais uniquement changer le nom de la société.
Exemple 1 : ETI - 510 av. de Jouques Bat B 13400 Aubagne France
Exemple 2 : Sileo Offshore - 510 av. de Jouques Bat B 13400 Aubagne France

Il faut enlever "ETI" au dessus de "TRANSMITTAL SHEET" et laisser vide.
Il faut enlever la case "Phase", sous "Contract NB".
Il faut renommer "Contract NB" en "Project", en indiquant le numéro et le libellé (exemple "15215 - PIL & BLUE".

Pouvez-vous s'il vous plait vous organiser tous les deux afin de décider lequel des 2 peut terminer cela ?
Merci !

![logo sileo light](https://cloud.githubusercontent.com/assets/4034223/12560106/263dd49c-c399-11e5-84ea-7e321371df47.png)
![logo eti light](https://cloud.githubusercontent.com/assets/4034223/12560107/2658ec28-c399-11e5-96ea-995852d3bb74.png)

**Comment by Talengi** [comment]
@providenz Voici une mise à jour du template de transmittal avec le Purpose of issue ajouté sur la ligne du document. Cela permettra donc de créer des transmittals avec des documents transmis avec un pupose of issue (POI) pour info (FI), comme pour revue (FR).
[template TRS modif MLA 28012016.pdf](https://github.com/Talengi/phase/files/107839/template.TRS.modif.MLA.28012016.pdf)

**Comment by Talengi** [comment]
@providenz @thibault 

Pour les outgoing transmittals : comme discuté avec Thibault la semaine dernière, il y aura une catégorie par recipient. C'est à dire que si ETI envoie des transmittals à Shell et BP, alors il y aura 2 catégories de transmittals dans l'organisation ETI. 
Le but est que chaque recipient (Shell ou BP) ne puisse accéder qu'à ses transmittals en se connectant à Phase et que chaque catégorie de transmittal soit numérotée en séquence (0001, 0002, 0003, etc.). 
Donc à chaque fois que ETI ou SIleo auront un nouveau tiers à qui envoyer des transmittals, il faudra crééer une nouvelle catégorie.
Ca vous parait clair ?

**Comment by providenz** [comment]
Très clair
