### ISSUE TITLE
Contenu du bouton action depuis le formulaire standard de document

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#254]
@thibault @providenz Il faudrait modifier comme suit le contenu du bouton action lorsque l'on clique dessus depuis le formulaire standard de document : 
- Enlever la phrase "Be careful!", ainsi que la petite icône de danger
- Renommer "Delete latest revision" en "Delete last revision"

**Comment by providenz** [comment]
Fermé par b8a4e69b76a83e1d89ac0843fe283d564811eca2
