### ISSUE TITLE
Griser le champ Purpose of issue si un document est juste interne

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#255]
@thibault @providenz Dans le formulaire standard de document, lorsque l'on créé ou révise un doc, est-il possible de griser le champ "Purpose of issue" si l'on sélectionne la valeur "Yes" dans le champ "Internal review only?" ?
La logique voudrait que si le doc est uniquement à vocation interne (et ne sera donc pas transmis par transmittal), on ne puisse pas dire si il sera pour info ou revue sur un transmittal.

**Comment by providenz** [comment]
@Talengi quel est le comportement attendu dans le cas suivant:
* j'ai créé un document qui n'est pas en  "Internal review only" et dont le "purpose of issue" n'est pas vide
* j'édite la révision et je le modifie en "Internal review only"
On grise simplement le champ Purpose en lui laissant sa valeur initiale ou on lui donne une valeur vide ?

**Comment by Talengi** [comment]
@providenz On grise et on lui donne une valeur vide.

**Comment by providenz** [comment]
Fermé par 9770b3671276a2df673ea3c7a1b425589cfeb932
