### ISSUE TITLE
ACL des téléchargements de fichiers

### ISSUE THREAD

**Issue by thibault** [Talengi/phase#261]
Le téléchargement de fichier (docs et pdfs) vérifie bien que l'utilisateur est connecté, mas il n'y a pas de vérification des droits d'accès au niveau de la catégorie.

cf. `documents.views.ProtectedDownload`

**Comment by thibault** [comment]
@Talengi Bon, ce n'est pas trivial, d'autant qu'il y a d'autres types de fichiers qui présentent le même problème :
 - les commentaires de revue
 - les commentaires sur les transmittals

Il va falloir définir un nouveau schéma d'url pour les télécharger, pour permettre de vérifier les droits d'accès.

Il faut également définir le niveau pertinent de contrôle. Est-ce qu'on peut conserver le fait qu'on effectue la vérification au niveau de la catégorie ? Ex : un utilisateur qui a accès à la catégorie sileo > swivel development a accès à tous les fichiers uploadés dans cette catégorie.

**Comment by providenz** [comment]
La difficulté c'est qu'on peut gérer les ACL sur la page qui affiche le lien mais c'est moins évident dans la vue qui livre le fichier.

Est ce qu'on ne pourrait pas procéder en deux étapes:
* générer une url de téléchargement difficile à forger en utilisant une fonction cryptographique. 
* déchiffrer cette url dans la vue qui livre le fichier ? Si l'url a été forgée elle ne sera pas déchiffrable et le fichier ne pourra pas être téléchargé?

**Comment by Talengi** [comment]
@thibault @providenz Je propose de raisonner ainsi : j'ai compris qu'à ce jour, on peut continuer à vivre avec ce bug. Il n'impacte pas l'utilisation de l'appli, mais présente une faislle de sécu/permissions, c'est bien cela ?
Si c'est le cas, Thibault je propose que tu avances sur le Trello et que l'on voit ce ticket pour plus tard. Je préfère avancer sur le fonctionnel dans la mesure ou ce problème d'ACL n'est pas génant à court terme.
OK ?

**Comment by thibault** [comment]
@Talengi Je pense que la solution de @providenz est la meilleure. On ajoute une composante aléatoire dans l'url qui fait qu'il est impossible de deviner l'adresse d'un éventuel fichier en vue de le récupérer illégalement.

**Comment by Talengi** [comment]
@thibault @providenz OK mais dans ce cas là, comment peut-on envoyer l'URL d'un document à un collègue ? A ce jour nous n'avons pas de fonction permettant d'envoyer un lien vers un doc, car il est simple de copier l'URL du doc et de l'envoyer à quelqu'un par email, IM ou en mettant une remarque dans Phase.
Est-ce que du coup cette nouvelle méthode empècherait cela ?
Par ailleurs, est-ce que cela serait quelque chose de super compliqué à faire ou pas ?

**Comment by thibault** [comment]
@Talengi Ça n'empêcherait pas de copier / coller l'url. Aujourd'hui, la faille de sécurité vient du fait qu'il est relativement facile de comprendre comment sont fabriquées les urls d'un documents, de taper une url forgée à la main dans la barre d'adresse et de récupérer ainsi un document frauduleusement.

Ajouter une petite composante aléatoire dans l'url empêche cette méthode, mais si on la récupère par d'autres moyens (e.g par mail ou im), on peut toujours récupérer le fichier.

En ce qui concerne la difficulté, ça ne me paraît pas insurmontable. Il faut simplement réfléchir à la façon dont on gère les fichiers existants.

**Comment by Talengi** [comment]
@thibault OK alors je confirme que l'on avance sur les notifs liées aux outgoing transmittals, et tu pourras attaquer cet item ensuite. OK ?
Merci !

**Comment by thibault** [comment]
Autres fichiers à "privatiser" .

 - file transmitted du formulaire de document ;
 - commentaires de liste de distributions ;
