### ISSUE TITLE
Vérifier que la modification d'une liste de distribution prédéfinie fonctionne

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#264]
@thibault J'ai créé un document ici : http://phase.talengi.com/sileo/pecan-hub-fpso/GX403-0987/
J'ai créé ce document, sélectionné une liste de distribution prédéfinie, l'ai modifiée en enlevant un reviewer et ça a buggé.

J'ai ensuite supprimé toute la liste de distribution, sauvegardé, édité, sélectionné une liste, l'ai modifiée et là ça a marché.
Peux-tu me dire si après avoir sélectionné une liste de distribution prédéfinie, il est possible de la modifier ? Car 1 fois sur 2 ça a marché chez moi.

**Comment by thibault** [comment]
@Talengi Les seuls moments ou l'on empêche de modifier les reviewers, c'est quand la revue est déjà passée à l'étape du leader. Mais dans ce cas, un message explicite décrit la cause.

Pour aller plus loin, il me faudrait plus de détails sur les bugs que tu as rencontré.

**Comment by Talengi** [comment]
@thibault Message d'erreur en rouge qui me disait "17 is not a valide value" ou quelque chose comme ça.

**Comment by thibault** [comment]
@Talengi J'ai compris. Quand on créé une liste de distribution, il est possible de sélectionner parmi tous les utilisateurs. Mais si ces utilisateurs ne font pas partie de la catégorie de ton document, alors la validation des données ne se fera pas et tu aura une erreur en soumettant le formulaire.

Le problème, c'est qu'au moment ou l'on créé la liste de distribution, la catégorie n'est pas encore renseignée, et on ne peut pas filtrer les utilisateurs proposés au préalable.

Je vais voir ce que je peux trouver pour régler le problème.

**Comment by Talengi** [comment]
@thibault En effet, ça fait sens, bien vu !
Du coup, ça risque d'être compliqué non ?
Pour le moment, dans le contexte de SIleo ça marche puisque tous les utilisateurs ont accès aux 3 catégories de docs. Mais potentiellement, ça peut déconner par la suite si ils mettent en place des droits plus limités.

**Comment by thibault** [comment]
@Talengi J'ai ajouté des tests au moment de la création de la liste de distribution.

En revanche, il est toujours possible que d'autres opérations rendent les données caduques, e.g si un utilisateur est sorti d'une catégorie après-coup.

Il me semble très difficile de prendre tous les événements en compte sans construire une usine à gaz, mais je pense qu'il n'y aura quasiment jamais le problème.

**Comment by Talengi** [comment]
@thibault Oui tu as raison.
Pour répondre aux 2 cas de figure que tu décris, est-il possible d'écrire un message d'erreur générique du type "The user <username> does not have the permission to be in review of this document. Please check with your administrator".
Tu en penses quoi ?
