### ISSUE TITLE
Document créé qui n'apparait pas dans la liste de doc

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#266]
@thibault J'ai encore ce problème de document qui n'apparait pas dans la liste de doc lorsque j'en créé un.
Il faut à nouveau que je rafraichisse la page. Ca m'arrive sur Firefox et j'ai désactivé les extensions. Je vais essayer avec Chrome.
Peux-tu regarder de ton côté stp ?

**Comment by thibault** [comment]
@Talengi Le problème est vraissemblablement dû à la manière dont ES gère ses résultats.

Il existe une commande spéciale « refresh » qui indique à ES de rendre tous les derniers traitements disponibles. Je ne sais pas comment j'ai pu louper ça jusqu'à maintenant.

À la prochaine livraison, ce problème devrait être réglé.

**Comment by Talengi** [comment]
@thibault OK ça marche. Dans ce cas, on s'assurera bien que c'est livré sur tous les environnements.
