### ISSUE TITLE
Affichage des champs dans le formulaire

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#27]
@thibault Je reviens sur ce point.
Lorsque l'on est en lecture seule sur un formulaire, on a aujourd'hui des champs qui ne s'affichent pas de la même manière. Il faudrait les homogénéiser, afin qu'ils aient tous à peu près la même apparence.
Par exemple, les champs document number et title, affichent le texte en gris clair : c'est difficile à lire et lorsque ton oeil descend sur les menus déroulants, tu n'as pas le même visuel, c'est bien mieux lisible.

Peux-tu s'il te plait mettre tous les champs avec une police foncée ?
Peux-tu également enlever l'icône qui apparait à côté du pointeur de la souris lorsque tu pointes sur un champs ?

**Comment by thibault** [comment]
@Talengi Vu que ce bug a déjà un an, peux-tu refaire une passe dessus et me confirmer le rendu définitif que tu souhaites obtenir pour le formulaire de document, en précisant : 

 * couleur souhaitée pour le fond des champs (blanc, gris)
 * couleur souhaitée pour la police (noir, gris foncé)
 * présence ou pas d'icones pour les champs en lecture seule / désactivés

Merci.

**Comment by Talengi** [comment]
@thibault Je confirme le message du 20 oct 2014 : il faut que les champs aient un fond blanc comme sur Github, qu'ils soient en cours d'édition ou en lecture seule.
Actuellement, le fond des champs est gris en lecture seule et blanc en édition. Il faut donc faire en sorte que les champs soient sur fond blancs également lorsqu'ils sont en lecture seule.
Police noire standard.
Pour les champs automatiquement remplis par l'application, on peut surement les laisser sur fond gris, car je ne vois pas quel type d'icone utiliser. SI tu as une idée, n'hésite pas à priposer.

**Comment by thibault** [comment]
@Talengi J'ai fait des modifs de style que j'ai livré en recette. Ça s'affiche correctement avec des versions récentes de firefox et chrome. Je suis en train de tester avec IE.

En revanche, je n'ai aucun moyen de tester avec une version récente de safari, qui ne sont disponibles que pour mac.

Note que je n'ai fait qu'une livraison partielle. Il est possible que des plantages surviennent jusqu'à la livraison complète.

**Comment by Talengi** [comment]
@thibault C'est pas mal du tout sous Firexox sur PC. Je testerai sur Mac chez moi.
QUestion supplémentaire : est-ce qu'il est possible de conserver la possibilité de sélectionner du texte contenu dans les champs ?

**Comment by thibault** [comment]
@Talengi Bonne question. Je vais regarder ça.

Je suis en train de faire tourner l'import chez moi. Ça va prendre une heure ou deux avant que je puisse finaliser la livraison.

**Comment by Talengi** [comment]
@thibault OK ça marche.
En fait pour les champs, faudrait juste trouver comment github ont fait et c'est tout. Mais j'imagine que ça ne se trouve pas comme ça...

**Comment by thibault** [comment]
@Talengi Peux-tu préciser de quel formulaire dans github tu parles ?

**Comment by Talengi** [comment]
@thibault Celui dans lequel je suis actuellement en train d'écrire par exemple

**Comment by thibault** [comment]
@Talengi Ok. Je te propose d'en discuter tout à l'heure.

**Comment by thibault** [comment]
Pas de news sur ce tickets et il y a eu des devs sur le sujet depuis. Je clos le ticket. En créer un autre si nécessaire.
