### ISSUE TITLE
Quels documents apparaissent dans la vue "Ready for outgoing TRS"

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#270]
@thibault Vu qu'il est à présent possible d'envoyer un document par outgoing transmittal, sans l'avoir revu, est-ce que ce document va directement apparaitre dans la vue "ready for outgoing TRS" une fois créé ?

**Comment by thibault** [comment]
@Talengi Oui, si un document peut être embarqué en l'état dans un transmittal, il sera listé dans les « ready for outgoing trs ».

Pour être précis, pour qu'une révision soit « transmittable » les conditions exaustives sont les suivantes : 
 - la révision n'est pas marquée en « internal review » ;
 - la révision n'est pas déjà embarquée dans un transmittal ;
 - la révision est bien la dernière révision.
