### ISSUE TITLE
Mise à jour Django ?

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#272]
@thibault Une mise à jour de sécurité de Django a été publiée. Est-ce que cela vaut la peine de la mettre ?

**Comment by thibault** [comment]
@Talengi J'ai mis à jour django à la dernière version de la 1.8.x.

Les tests passent corrtement, et je n'ai pas rencontré d'erreurs à première vue, mais il faudra être extra-attentif les prochains jours. Ce genre de mise à jour est censé ne pas provoquer de changements, mais on n'est jamais à l'abri d'une petite régression difficile à détecter.
