### ISSUE TITLE
Perte du contract number en éditant ou révisant un transmittal

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#288]
@thibault Je suis sur le serveur Talengi : lorsque j'édite ou révise un transmittal, le champ contract number devient vide et ne me permet pas de sélectionner une valeur. Alors que juste avant il était rempli. Comme c'est un champ obligatoire, je suis bloqué pour finaliser le processus.
Peux-tu regarder stp ?

**Comment by thibault** [comment]
@Talengi À priori, il faut spécifiquement assigner les contracts number dans l'admin à la catégorie outgoing transmittal. C'est lié aux dernières évolutions sur les contract number.

J'ai assigné les contract number à toutes les catégories dans l'admin en attendant.

**Comment by thibault** [comment]
@providenz Est-ce qu'on peut trouver une solution à ce problème :

0) Je créé un contract number « toto », je l'assigne à la catégorie « outgoing transmittal »
1) Je créé un contract FAC09001 dans l'admin, je l'assigne à « swivel dev »
2) je créé un transmittal avec des documents de swivel dev, le transmittal reçoit le contract FAC09001
3) j'édite le transmittal. Comme FAC09001 ne fait pas partie des champs disponibles, c'est la valeur « toto » qui est sélectionnée par défaut. À mon insu, j'ai modifié le transmittal.
4) le nom du document et le contract number ne sont plus cohérents, la fonction qui trouve le prochain numéro de transmittal s'emmêle les pinceaux et ça plante.

**Comment by thibault** [comment]
@Talengi Le ticket a été traité par @providenz. J'ai juste une question avant de fermer le ticket.

Maintenant, les champs « originator » et « contract number » du formulaire des outgoing transmittals sont en lecture seule, ce qui me parait logique.

Peut-on partir du principe que le champ « recipient » devrait lui aussi être en lecture seule ?

**Comment by Talengi** [comment]
@thibault Lorsque tu créés le transmittal, tu dois pouvoir sélectionner le recipient et le numéro de contrat. Mais lorsque le transmittal a été créé et que tu édites le formulaire, tu ne devrais en effet pas pouvoir modifier le recipient, tu as raison. 
Il faut être obligé de supprimer un transmittal pour faire une modification sur un numéro. Don cen effet, grisons le champ recipient aussi afin de prévenir cela.
Peux-tu le faire stp ?

**Comment by thibault** [comment]
@Talengi Ok. Dernière (j'espère) question, ne devrait-on pas aussi bloquer le document number des outgoing transmittals, tant qu'on y est ?

**Comment by Talengi** [comment]
@thibault Oui tu as raison, tu peux le faire aussi. Merci.
