### ISSUE TITLE
Test sur le type "str"

### ISSUE THREAD

**Issue by thibault** [Talengi/phase#289]
Dans pdf_eti.py, il y a un test sur une valeur de configuration qui doit être « str ».

En production, comme les chaînes étaient de type « unicode », le test n'est pas passé et l'appli a crashé.

Il faudrait utiliser six pour vérifier si la chaîne est un champ texte (str ou unicode) et remplacer l'exception par une assignation de valeur vide, pour éviter de planter toute l'appli en cas de problème de configuration.

**Comment by providenz** [comment]
J'ai modifié les checks et j'ai essayé de prendre tous les cas en compte. Je pense que les quelques disparités de comportements entre les différentes install sont liées à l' unicode_litterals qui n'est pas dans tous les fichiers de confs privés. 
En cas de mauvaise conf, c'est loggué en warning.
