### ISSUE TITLE
Impossible de démarrer une revue sur un document

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#293]
@thibault Je n'arrive pas à démarrer de revue sur le serveur Talengi.
J'ai créé 2 documents : 
- http://phase.talengi.com/eti/swivel-development/XX-505-PIP-0002/
- http://phase.talengi.com/eti/pil-bue/XX-504-PIP-DTS-0001/

Dans les deux cas j'ai bien défini une liste de distribution, mais je ne peux pas démarrer de revue. Depuis le formulaire de document, le bouton n'est pas présent dans le menu action. Depuis la liste de documents, je peux cliquer sur "start review", j'ai bien la pop up avec la progress bar, mais ensuite, j'ai le message suivant : We failed to start the review for the following documents: XX-505-PIP-0002

Peux-tu regarder en priorité ?

**Comment by Talengi** [comment]
@thibault J'ai le même problème sur le serveur de Sileo.

**Comment by Talengi** [comment]
est-ce en lien avec #291 ?

**Comment by thibault** [comment]
@Talengi Correction livrée en recette.

**Comment by Talengi** [comment]
@thibault J'ai démarré les revues sur les 2 docs mentionés plus haut.
J'obtiens des notifs différentes. Pour le premier doc, la revue a été lancée depuis le formulaire, pour le 2nd, la revue a été lancée depuis la liste en mettant une remarque.

Peux-tu regarder pourquoi cela fait ça ?

**Comment by thibault** [comment]
@Talengi J'ai un doute alors je reformule pour que tu me confirmes que j'ai bien compris le problème.

Tu as démarré deux revues sur deux documents avec deux méthodes différentes. Tu as obtenu deux messages de notifications différents. Les revues fonctionnent correctement. Est-ce correct ?

**Comment by Talengi** [comment]
@thibault C'est exact

**Comment by thibault** [comment]
@Talengi C'est un comportement est normal, car ce sont deux actions différentes. Dans un cas, tu démarres une revue. Dans l'autre, tu démarres un ensemble de revues (même si un seul document est sélectionné). Tu penses que c'est perturbant pour l'utilisateur ?

**Comment by Talengi** [comment]
@thibault Tu as raison, c'est normal et il n'y a pas de raison de le changer, on reste comme ça.
