### ISSUE TITLE
Amélioration des exports CSV depuis les listes d'outgoing transmittals

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#307]
@thibault Peux-tu s'il te plait mettre en place les exports CSV d'outgoing transmittals afin qu'ils reprennent toutes les colonnes et toutes les infos présentes dans le formulaire d'un outgoing transmittal ?
Il faut faire attention à comment on gère les related documents d'un transmittal --> on en parle pour voir comment procéder si tu le souhaites.

**Comment by thibault** [comment]
@Talengi En ce qui concerne l'export des related documents, c'est difficilement gérable. CSV n'est pas un format approprié pour exporter des données de manière structurées.
