### ISSUE TITLE
Bouton Action vide dans formulaire des outgoing transmittals

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#310]
@providenz lorsque l'on est dans le formulaire d'outgoing transmittal et que l'on clique sur le bouton action, il ne se passe rien.
Peux-tu regarder cela stp ?

**Comment by providenz** [comment]
@Talengi Je ne reproduis pas le problème, j'ai bien le dropdown qui s'affiche quand on clique sur le bouton. Tu aurais plus de précision stp ?

**Comment by Talengi** [comment]
@providenz Que je sois sous Safari ou Firefox, j'ai le même problème. Je suis sur le serveur Talengi, connecté en tant que Virginie Pompier.

[action.zip](https://github.com/Talengi/phase/files/139070/action.zip)

**Comment by providenz** [comment]
Fermé par 1f8c34df9e38026ab5a6e0b32fc949180066c786

**Comment by Talengi** [comment]
@providenz J'ai encore le bug, peux-tu stp regarder.

**Comment by Talengi** [comment]
Je précise que cela se produit avec mon compte, pas avec celui de Virginie Pompier par exemple.

**Comment by providenz** [comment]
Il faut disposer des permissions nécessaires et sur cette installation appartenir au groupe `Document controller`

**Comment by providenz** [comment]
Ne pas afficher le boutton si le contenu du dropdown est vide. Fix dans 8f7156b7005fa9b4b473b4f12068a8490b205e03
