### ISSUE TITLE
Générer un template d'import de csv

### ISSUE THREAD

**Issue by providenz** [Talengi/phase#319]
En tant qu' utilisateur je peux télécharger un modèle de csv comportant les en-têtes correspondant aux modèle de document considéré.

**Comment by Talengi** [comment]
@providenz L'idée finale pour moi serait que lors de l'installation de Phase pour un client donné, il n'y ait rien ou pas grand chose à faire côté code pour que les templates CSV soient prêts à l'emploi. On en parle et tu me diras ce qui est possible ou pas, mais si on met en place l'appli, que l'on créé les modèles de données, si les CSV sont automatiquement générés, c'est génial.

**Comment by providenz** [comment]
Dans 1ed6b1a630a0e70e63de8a68b8af34dd3214b399

**Comment by Talengi** [comment]
@providenz J'ai les remarques suivantes : 
- Lorsque l'on télécharge un template CSV, il faut faire un traitement dans Excel pour que tous les champs soient mis en colonnes. N'est-il pas possible que cela soit fait avant ?
- Dans la section "Imports", je mettrai en premier la section "Download import template", mais en la renommant "Import templates", puis "Import document list", puis "List all imports"
- Dans la section "Import templates", renommer la phrase "Csv import template" en "CSV import templates"

**Comment by providenz** [comment]
Fix 98270d32c7f1e18a455c5c98ab857e1f35e0eb85
