### ISSUE TITLE
Activer ou désactiver les notifications emails depuis la section d'admin

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#322]
@providenz Permettre d'activer ou désactiver les notifications emails depuis la section d'admin.
A discuter en fonction de la complexité, voir si l'on peut activer/désactiver : 
- par type de notifications
- par utilisateur

**Comment by providenz** [comment]
Closed by a1496e54e9c8edb79435b03638287f365e9c3499

**Comment by Talengi** [comment]
@providenz Peux-tu s'il te plait apporter les modifications suivantes : 
- Renommer la phrase "Send reminders for trs with missing ack of receipt" en "Send reminders for outgoing transmittals with missing acknowledgement of receipt"

**Comment by providenz** [comment]
77d7fe7ecf80d3eef9f6588fc3657da3f0051af3
