### ISSUE TITLE
Contenu de l'email de création de compte utilisateur 

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#323]
@providenz Est-ce qu'il est possible de customiser l'objet et le contenu de l'email envoyé à un utilisateur lors de la création d'un compte ?
Si oui, je vais te préparer un contenu type.

**Comment by providenz** [comment]
@Talengi oui, il faut savoir qui va gérer ça parce qu'on a du contenu dynamique (nom d'utilisateur, url de mise à jour de mot de passe, domaine, url). C'est destiné à l'admin ?

**Comment by Talengi** [comment]
@providenz Tu as peut-être compris que je demandais si un admin fonctionnel pouvait faire les modifs lui même, c'est ça ?
Si on peut le faire, c'est super, moi je pensais juste à mettre en dur un modèle de mail de Phase qui est différent du standard Django.
Si un admin peut avoir une interface pour taper le texte type en gérant les champs dynamiques c'est super. Mais je pense que cela va être long à faire non ? Je pense qu'il est plus simple de rester sur le mécanisme actuel et que je te donne un contenu type et comme ça pas de risque de perturber les champs dynamiques.
On en parle si tu veux.

**Comment by providenz** [comment]
@Talengi Si je comprends bien la question, c'est déjà le cas: https://github.com/Talengi/phase/blob/master/src/templates/registration/activation_email.txt
Il faut définir:
* si le modèle est le même pour tout le monde, auquel cas il n'y a qu'à mettre à jour le template existant
* si tu souhaites une règle de personnalisation particulière

**Comment by Talengi** [comment]
@providenz Je me dis qu'éventuellement il faudrait une personnalisation en fonction d'un utilisateur interne ou externe (lié à une entité), mais je ne suis même pas sur que cela vaille le coup.
Je vais te préparer un texte pour mettre à jour le template.

**Comment by Talengi** [comment]
@providenz Voici le texte que je propose : 

Dear {{ username }},

Welcome to Phase!
Your account is now ready to use.

Click on the following link to personalise your password and start using the application:

{% url 'password_reset_confirm' uidb64 token as the_url %}
http://{{ site.domain }}{{ the_url }}

The Phase team.

**Comment by providenz** [comment]
Done d028f26653d0d5284d273300e1239b1d33e257db

**Comment by Talengi** [comment]
@providenz J'imagine que l'envoi d'emails est désactivé sur Talengi car j'ai créé un user mais ne reçois pas d'email ?

**Comment by providenz** [comment]
Settings mis à jour.

**Comment by Talengi** [comment]
@providenz Je peux paraitre chiant pour des broutilles, mais dans le messages, il manque la signature "The Phase team".
Tu peux rajouter ? Merci.

**Comment by providenz** [comment]
Désolé, j'aurais dû faire attention à ça. Réglé 3382a15037357727393e8e98af2a4b71378266d6
