### ISSUE TITLE
Liens hypertextes dans les remarques

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#328]
@providenz Lorsque l'on écrit une remarques au cours d'une revue, si l'on colle un lien hypertexte, celui-ci n'est pas cliquable. Il faut le selectionner pour soit faire un clic droit et "ouvrir le lien dans un nouvel onglet", soit copier/coller le lien dans un nouvel onglet.
N'est-il pas possible que le lien soit reconnu et cliquable ?

**Comment by providenz** [comment]
Oui, sous réserve que les urls soient bien formatées, aucun problème.

**Comment by providenz** [comment]
61fadea8873bc08f11062204f196c5aed73915d9
