### ISSUE TITLE
Affichage des documents liés à un outgoing transmittal depuis le formulaire

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#329]
@providenz J'ai l'exemple d'un transmittal que je viens de créer, dont je joins une copie d'écran.
On se retrouve avec un tableau ou la colonne title est toute petite et sur 3 lignes et la colonnes file transmitted est énorme par rapport aux autres.
Est-il possible de faire que les largeurs soient un peu moins grandes, quitte à masquer le nom de fichier et à la mettre en tooltip par exemple ?

**Comment by Talengi** [comment]
![doc lie a trs](https://cloud.githubusercontent.com/assets/4034223/13509686/feefe29c-e18c-11e5-83fa-7ebe69ba9cd5.PNG)

**Comment by providenz** [comment]
ad70589dcd8af9831abbdbfaa15dfc2d5740d60b

**Comment by Talengi** [comment]
@providenz C'est beaucoup mieux comme ça, merci ! Peux-tu juste faire en sorte que le tooltip s'affiche en bas. Il n'y a pas de solution miracle, mais en l'état, le tooltip masque la ligne concernée.
Pourrais-tu stp faire que le tooltip s'affiche en bas ?
