### ISSUE TITLE
Bug sur les remarques ?

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#335]
@providenz je me suis connecté en tant que Gaetan Mattoni. J'ai une notif me disant que j'avais été mentionné sur le doc GX909-ABCDEF_1623. Je clique dessus, j'arrive sur le formulaire du doc et là je vois que le bouton des remarques indique 0. Je clique dessus et je vois bien des remarques. Et là, le bouton affiche à présent 3 (il y a en effet bien 3 remarques.
On avait déjà eu ce bug il y a pas mal de temps avec Thibault : le bouton de remarques n'affiche pas le nombre réel.
Peux tu regarder ?

**Comment by providenz** [comment]
A priori pas de bug mais un cache pas mis à jour en prod.
J'ai ajouté une commande pour rafraîchir le cache. 492564cd419ffb83ce2987a73518d1bceb0e192f
