### ISSUE TITLE
Pas de formulaire qui s'affiche sur /eti/swivel-development/DOC-TST-LP-2/

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#340]
@providenz Lorsque tu cliques sur le document DOC-TST-LP-2 depuis la liste, tu arrives à cette URL, mais qui te met une page vide "this is not the page you are looking for"
Peux-tu regarder stp ?

**Comment by providenz** [comment]
Pb de désindexation, à investiguer.

**Comment by Talengi** [comment]
@providenz Je ne sais plus où on en était sur ce ticket ? Tu regardes pour le boucler ces jours-ci ?

**Comment by providenz** [comment]
On n'a pas eu de problème depuis plus d'un mois et pas de régression identifiée dans le code, je ferme.
