### ISSUE TITLE
Export de données au format Excel

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#343]
@providenz Ticket afin de tracer le travail réalisé hier.
Je viens de faire un essai et cela a l'air très bien !

Question : est-on capable de définir le format de date qui apparait dans l'Excel, ou bien est-on tributaires du format côté appli ?

**Comment by providenz** [comment]
On a plusieurs façons de le définir, de quelle manière souhaites-tu souhaites faire ça ?

**Comment by providenz** [comment]
8b99b1a2dc0fe58b8a8a9a80912840f200472a32
