### ISSUE TITLE
Identification des formats de cellule + champs obligatoires dans templates d'imports

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#349]
@providenz Peut-on mettre en ligne 2 (voir en ligne 3 pour un exemple à 2 révisions d'un même doc) une ligne qui présente les format de valeurs attendus dans chaque cellule.
Peut-on également visualiser les champs obligatoires ?

**Comment by providenz** [comment]
On se heurte à 2 difficultés:
* les champs requis pour l'import ne sont pas forcément les mêmes que ceux du modèle/document
* pour les exemples il faudrait aller piocher des valeurs dans la base, qui sera vide à l'installation de Phase, et donc au moment où l'utilisateur aura besoin de la fonction d'import.
A moins de spécifier cela dans le dictionnaire de config `import_fields` de chaque document, ça risque d'être un peu lourd à gérer.
