### ISSUE TITLE
Formulaire pour création transmittal

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#355]
@providenz Sileo me disent qu'ils vont avoir 5 ou 6 fournisseurs très vite et cela va continuer à monter rapidement. Les cases à cocher ne me semblent donc pas pratiques et ergonomiques pour la modale.
Ne pourrait-on pas avoir la possibilité de taper à la main les fournisseurs avec une auto completion ou un autre mécanisme permettant de sélectionner de multiples fournisseurs sans surcharger l'écran ?
Merci !

**Comment by providenz** [comment]
Oui on peut mettre un select comme pour la liste des reviewers.

**Comment by Talengi** [comment]
Je pense que c'est mieux en effet, on part là dessus.

**Comment by Talengi** [comment]
@providenz J'ai par ailleurs eu un bug : en tant qu'admin j'ai lancé une revue sur un document et l'appli m'a dit que le transmittal avait failed, mais pourtant j'avais bien des transmittals créés dans le formulaire du doc. Peux-tu regarder ?

**Comment by Talengi** [comment]
![capture](https://cloud.githubusercontent.com/assets/4034223/14030826/f89a01ce-f209-11e5-9cc2-bd9c92689b54.PNG)
@providenz Avec une capture d'écran de ce que cela donne

**Comment by providenz** [comment]
Mis à jour et corrigé dans 15e0f0f0a83b300ad1ae69a0f456c277677bbd1a
