### ISSUE TITLE
Incohérence sur un start review

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#368]
@thibault Peux-tu stp regarder le bug suivant : 
J'ai créé le doc https://phase.talengi.com/eti/swivel-development/GX999-502-AA-PID-1234/
J'ai créé une liste de distribution en admin et l'ai appliquée au document. J'ai démarré une revue avec remarques en mentionnant un reviewer et le leader. L'appli me dit qu'elle ne peut pas démarrer la revue avec le message suivant dans les notifications : "The review on revision 01 of the document GX999-502-AA-PID-1234 (Test Matthieu du jeudi matin 14/04/2016) cannot be started"
Mais lorsque je regarde le tableau de la liste de distribution, les reviewers sont bien in progress et le leader est bien pending.
Peux-tu regarder ?
Merci!

**Comment by thibault** [comment]
@Talengi J'ai créé un document dans des conditions similiaires et n'ai pas pu reproduire le problème. Parviens tu à reproduire le bug ?

**Comment by Talengi** [comment]
@providenz Peux-tu stp tester et me dire si tu reproduis ce bug ou non ?

**Comment by providenz** [comment]
@Talengi même chose, j'ai créé un doc de test similaire et je n'ai pas reproduit le pb, la notif est cohérente avec l'état "under review" du doc.
