### ISSUE TITLE
Audit trail - Remarques

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#376]
@providenz Quelques demandes d'améliorations sur l'audit trail : 
- Lorsque l'on créé une nouvelle révision, peut-on afficher quelque chose comme "Matthieu Lamy created revision 02 of FAC10005-EMS-000-INS-OPM-0001" au lieu de "Matthieu Lamy created FAC10005-EMS-000-INS-OPM-0001 (2) on FAC10005-EMS-000-INS-OPM-0001" ?
- Lorsque l'on démarre une revue, peut-on afficher quelque chose comme "Matthieu Lamy started review on FAC10005-EMS-000-INS-OPM-0001 rev 02", au lieu de "Matthieu Lamy started review FAC10005-EMS-000-INS-OPM-0001 (2)" ?

Sinon je me dis, est-ce que l'on ne peut pas présenter les infos sous forme de tableau ? Cela évite du coup de se prendre la tête sur le wording. Tu en penses quoi ? On pourrait avoir les colonnes suivantes : User, Action type, Document, Revision, Date & time

C'est jouable ? Si oui, on peut faire un essai ?

**Comment by Talengi** [comment]
@providenz Pour cette carte : 
- Je crois que l'on avait dit que la vue en tableau serait compliquée, c'est bien cela ?
- Est-ce que l'on peut afficher la révision soit le bon format sans parenthèses en indiquant à chaque fois "rev XX" ?
- dans la phrase "user3_pfx reviewed GX-502-AB-8901 (1) on GX-502-AB-8901", pourquoi le doc number est-il répété, et peut-on ne pas le voir une 2nde fois ?
- Peux-tu remplacer par exemple "user1_pfx started review GX-502-AB-8901 (1)", par "user1_pfx started review on GX-502-AB-8901 rev 01" ?
- Peux-tu remplacer "user3_pfx reviewed GX-502-AB-8901 (1) on GX-502-AB-8901" par "user3_pfx reviewed GX-502-AB-8901 rev 01" ?
-

**Comment by providenz** [comment]
Done #431
