### ISSUE TITLE
Graphiques - Remarques

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#377]
@providenz Voici quelques remarques sur les graphiques : 
- Les bordures droite et bas de chaque graph présente une zone qui semble pouvoir permettre de scroller haut ou bas. Est-ce que l'on peut faire disparaitre ces bandes ?
- Peut-on ajouter un graphique permettant de voir le nombre de documents en cours de revue pour chaque utilisateur ? Sous forme de bar chart, les utilisateurs présentés à l'horizontale et le nombre de docs à la verticale, ne présentant que les noms des personnes qui ont actuellement des docs en cours de revue (on ne liste pas des utilisateurs qui n'ont pas de documents)
- Peut-on ajouter un graphique permettant de voir le nombre de documents en retard pour chaque utilisateur ? Sous forme de bar chart, les utilisateurs présentés à l'horizontale et le nombre de docs à la verticale, ne présentant que les personnes qui ont actuellement des docs en retard (on ne liste pas des utilisateurs qui n'ont pas de documents)
- Dans le graphique "Number of documents reviewed by month", mettre l'axe horizontal à 1 digit, sans virgule, allant de 0, 1, 2, 3, 4, etc...
- Sur les graphs "Number of documents received by month" et "Number of documents reviewed by month", peut-on décaler la première date un peu sur la droite ? J'aimerai que la 1ere valeur ne démarre pas au croisement des 2 axes

**Comment by Talengi** [comment]
Exemple d'affichage d'un des graphiques sous Firefox sur Windows ![graph firefox windows](https://cloud.githubusercontent.com/assets/4034223/14976648/5f927cc0-1105-11e6-993c-895c12fdad0b.PNG)

**Comment by Talengi** [comment]
exemple de graph sur excel avec démarrage des données horizontales décalées à droite
![graph excel](https://cloud.githubusercontent.com/assets/4034223/14976733/2682de4c-1106-11e6-9e69-b04a65f3023a.PNG)

**Comment by Talengi** [comment]
@providenz Je mets de nouvelles remarques en passant : 
- Peut-on essayer une couleur de fond moins foncée, voir peut-on essayer de mettre les graphs sur un fond blanc ?
- Pourras-tu centrer horizontalement les titres des graphs (à priori valable pour les camenberts) ?

Merci.

**Comment by providenz** [comment]
Fait dans 7a21716f4427ea1830139a361c61bf9f4936ef20
