### ISSUE TITLE
Permettre de faire des exports Excel et CSV des dernières révisions uniquement

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#387]
@providenz A ce jour, lorsque l'on fait un export Excel ou CSV d'une liste de documents, on obtient l'ensemble des révisions de chaque document de la liste.
Pourrais-tu mettre en place un mécanisme permettant de n'exporter que la dernière révision des documents ?
- Soit on reste sur le menu déroulant actuel permettant de sélectionner le format CSV ou Excel, puis une pop-up apparait demandant de sélectionner "All revisions" ou "Last revisions".
- Soit on fait une pop-up sur le même modèle que le "Download documents" permettant de sélectionner le format et si l'on veut "All revisions" ou "Last revisions".

On en parle.

**Comment by providenz** [comment]
Actuellement l'export correspond bien aux dernières révisions. Donc j'implémente un export pour toutes les révisions ?

**Comment by Talengi** [comment]
@providenz Je n'ai pas fait de vérif, mais j'avais en tête que c'était l'inverse.
Oui tu mets en place la possibilité d'exporter pour toutes les révisions.
Merci !

**Comment by providenz** [comment]
Done dans #389
