### ISSUE TITLE
Permettre de sélectionner du texte à l'intérieur des cellules des formulaires de documents

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#388]
@providenz J'imagine que cette demande va être moins triviale qu'il n'y parait et nous en avions parlé il y a longtemps avec Thibault.
A ce jour, il n'est pas possible de sélectionner les valeurs contenues dans tous les champs des formulaires de documents lorsque l'on est en lecture seule. Et en plus cela dépend du navigateur utilisé. Chrome permet de sélectionner le document number et le title, mais pas l'originator par exemple. Firefox ne te permet aucun de ces 3 champs.
D'expérience, c'est super pratique au quotidien de pouvoir le faire et il faudrait le mettre au propre sur Phase (sur le même modèle que Github : le texte que l'on saisit dans les champs est sélectionnable).
On en parle.

**Comment by providenz** [comment]
Done dans #390

**Comment by Talengi** [comment]
@providenz Je suis sur Mac/Safari : je peux bien sélectionner du texte dans les champs, mais si je colle une valeur copiée dans un des champs, cela remplace à l'écran la valeur qui est enregistrée. Cela ne modifie pas la valeur enregistrée, mais c'est perturbant de voir que tu peux modifier une valeur à l'écran.
Est-ce que tu peux faire quelque chose pour que cela n'arrive pas ?

**Comment by providenz** [comment]
Cf #396

**Comment by Talengi** [comment]
@providenz Tout semble bon à présent.

**Comment by Talengi** [comment]
@providenz Si tout est bon pour toi là dessus, tu peux fermer le ticket.
