### ISSUE TITLE
Bug sur la fonction de téléchargement de fichiers

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#391]
@providenz Impossible de télécharger des fichiers en batch depuis la liste de documents (Actions / Download). On tombe à chaque fois sur une page "Whoops".
Peux-tu corriger ?

**Comment by providenz** [comment]
Ce problème est dû à des fichiers inexistants. Au cours de l'évolution de phase, des fichiers ont du être supprimés ou déplacés sans que ce soit répercuté dans la base.

**Comment by providenz** [comment]
J'ai jouté une vérification pre-téléchargement. En cas de défaut, l'erreur est logguée.
cf #402
