### ISSUE TITLE
Volet de menu latéral gauche + volet de notifications

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#392]
@providenz Aujourd'hui, il faut cliquer sur les croix pour fermer un volet latéral. Est-il possible de faire en sorte que dès que l'utilisateur clique ailleurs dans l'interface, le volet se ferme ?

**Comment by providenz** [comment]
Cf. #397

**Comment by Talengi** [comment]
@providenz Cela me semble ok de mon côté. Tu peux fermer une fois que tu confirmes avoir terminé là dessus.
