### ISSUE TITLE
Modification de la couleur de la barre de menu noire et de ses incones

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#394]
@providenz La barre de menu tout en haut de l'interface est aujourd'hui noire et je trouve cela un peu agressif à l'oeil à force.
Pourrais-tu stp essayer de la mettre à la même couleur que la barre équivalente de Github, qui est dans un gris-blanc ?
Du coup il faudrait que : 
- l'icône du volet latéral gauche devienne noire et sans encadrement
- le texte soit écrit en noir
- l'icone de notification soit noire et sans encadrement

**Comment by providenz** [comment]
CF  #397

**Comment by Talengi** [comment]
@providenz Mes remarques : 
- J'ai l'impression que le bouton de menu en haut à gauche est un peu flou, non ? Par ailleurs, il est un peu gros par rapport à l'icône de notifications. Est-ce que tu peux le réduire un peu de taille ?
- Peux-tu mettre l'ensemble du texte de la barre en noir (le breadcrumb a l'air noir, mais le menu avec le nom d'utilisateur et l'icône des notifications sont plus gris que noirs) ?

**Comment by providenz** [comment]
CF  #399

**Comment by Talengi** [comment]
@providenz Peux-tu stp noircir l'icône de notification (comme sur Github) ?

**Comment by providenz** [comment]
Fait dans #403
