### ISSUE TITLE
Prio 1 pour aujourd'hui - Permissions spécifiques

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#395]
@providenz A ce jour nous avons un groupe d'utilisateurs "document controller" qui permet de créer, diffuser, supprimer des documents dans l'appli.
Est-ce que l'on peut mettre en place un groupe qui permet de créer des documents, les diffuser, mais pas de les supprimer ?
Si oui, peut-on appeler ce groupe "project engineer" ?

**Comment by providenz** [comment]
Le mécanisme déjà en place permet de créer un groupe capable de créer et modifier des documents sans pouvoir les supprimer.

Est-ce que le groupe  "project engineer" doit également pouvoir créer des transmittals, et démarrer/arrêter des reviews ?

**Comment by Talengi** [comment]
@providenz On va changer de nom, ce sera un groupe qui s'appellera "Assistant", plutôt que "Project Engineer". Désolé !
Ce groupe doit pouvoir démarrer/arréter des revues, mais pas faire d'outgoing transmittals.

**Comment by Talengi** [comment]
@providenz Désolé, nouvelle motif : le groupe ne permet que de créer et réviser des documents, pas de lancer ni d'arrêter des revues.

**Comment by Talengi** [comment]
@providenz Ca me parait bon pour les permissions. Ca fonctionne comme attendu.
Est-ce que tu peux livrer ces modifs (l'ensemble) sur le serveur de test de Sileo ce matin ?

**Comment by Talengi** [comment]
@providenz Pardon, livre sur le serveur de test lorsque tu as corrigé le bug sur les téléchargements de fichiers
