### ISSUE TITLE
Section FEEDS - Affichage du nom de l'utilisateur ayant réalisé une action

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#400]
@providenz La section FEEDS a été conçue par Thibault.
Il y a une sous section "New documents" qui liste les documents qui ont été créés dans l'application.
Est-ce que tu pourrais faire apparaitre pour chaque document une ligne "Created by" qui indique le nom de l'utilisateur qui a créé le document ?
Tu peux faire apparaitre cette info en dernière ligne de chaque doc.

**Comment by providenz** [comment]
Done dans #405 et #406
