### ISSUE TITLE
Message affiché lorsque l'on a pas de favoris

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#401]
@providenz Lorsqu'un utilisateur se rend dans la section "Favorites" et que celui-ci n'a pas sélectionné des documents comme favoris, Phase affiche le message suivant "You do not have any favorite document."
Est-ce que tu pourrais remplacer ce message par "You do not marked any document as favorite."

**Comment by Talengi** [comment]
@providenz Correction suite à discussion : You do not have any document marked as favorite."

**Comment by providenz** [comment]
Done dans #404
