### ISSUE TITLE
Insertion du logo Talengi sur la page de connexion

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#411]
@providenz Peux-tu stp : 
- Insérer le logo Talengi (que je joins à ce ticket) sur la page d'accueil de phase.talengi.com, en bas à droite
![logo](https://cloud.githubusercontent.com/assets/4034223/16023590/b32bd704-31bd-11e6-8399-04c102a97e70.png)

**Comment by providenz** [comment]
Done in #415

**Comment by Talengi** [comment]
@providenz J'avais dit en bas à droite, pas centré :)
Peux-tu mettre en pied de page, en bas à droite ?
Merci !

**Comment by providenz** [comment]
Fix dans  #421
