### ISSUE TITLE
Homogénéiser l'affichage du breadcrumb des reviews

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#413]
@providenz 
Je vois sous Safari que le breadcrumb des reviews ne s'affiche pas de la même manière que lorsque l'on est dans une liste de documents.
Est-ce que tu pourrais faire les modifs afin que l'affichage soit le même que dans les listes de documents avec le séparateur ">" entre organisation et catégorie de document ?

**Comment by providenz** [comment]
Done in #415
