### ISSUE TITLE
Modification du "Ready for outgoing TRS"

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#428]
@providenz Une case à cocher "Ready for outgoing TRS" est disponible dans la barre de recherche.
Ce bouton était à l'origine là pour identifier les documents qui ont une revue terminée. Entre temps, nous avons modifié le comportement de l'appli pour les outgoing transmittals et tous les documents peuvent être envoyés avec un transmittal, qu'ils aient été revus ou pas.
Pourrais-tu donc apporter les modifications suivantes : 
- Modifier le label de la case à cocher en "Closed reviews"
- Lorsque la case est cochée, il faudrait n'afficher que les documents qui ont une revue terminée et qui attendent d'être envoyés avec un outgoing transmittal (ne sont donc listés que les docs dont la revue est terminée et qui ont un "YES" dans le champ "Internal review only?"

**Comment by providenz** [comment]
Done dans #429
