### ISSUE TITLE
Droits d'accès de l'api users

### ISSUE THREAD

**Issue by thibault** [Talengi/phase#44]
L'api user permet d'accéder à la liste de tous les utilisateurs quelque soient les droits d'accès de l'utilisateur loggué. Les modalités d'accès sont à définir.

**Comment by thibault** [comment]
@Talengi L'api permettant de lister les users est utilisée pour afficher les formulaires de sélection d'utilisateur (reviewers, leader, approver) du formulaire de document avec de l'autocomplétion.

Quelles sons les droits d'accès à implémenter ? Est-ce qu'un doc controller peut lister tous les utilisateurs ? Uniquement ceux de l'organisation ? De la catégorie ? Autre ?

**Comment by Talengi** [comment]
@thibault Le Doc Controller ne peut indiquer que les gens d'une même catégorie, au sein d'une organisation donnée.
