### ISSUE TITLE
Nombre d'items à revoir indiquant 0 alors que des documents sont bien en revue

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#54]
@thibault En lançant une revue en batch sur plusieurs documents depuis la liste et sans avoir touché aux listes de distribution doc par doc, les nombre d'items affichés dans les champs reviewer, leader et approver restent à zéro. En rentrant dans chaque section, je vois qu'il y a bien des documents à revoir.

Peux-tu regarder ? Est-ce qu'il faut obligatoirement indiquer à l'utilisateur qu'il doit editer la dernière revision et mettre à jour la liste de distribution pour que le mécanisme fonctionne ?

**Comment by Talengi** [comment]
@thibault Il semblerait que la fonction "Start review" sur plusieurs documents en meme temps ne fonctionne plus. Tu peux regarder ?

**Comment by thibault** [comment]
@Talengi 

Il y avait deux problèmes :

1) La fonction de batch start review ne marchait pas, c'est corrigé.
2) Les compteurs de nombre d'items ne marchaient pas.

Pour ce deuxième bug, il s'agissait d'un problème de cache.

Le cache est utilisé à divers endroits dans le projet. Le problème est que l'on utilisait aucun serveur de cache, et on se contentait de tout mettre en mémoire. Ça fonctionne pour des applications très simples et en environnement de dev, mais ça ne marche plus dés que l'application grossit en complexité et utilise plusieurs applications. En effet, chaque processus dispose de sa propre mémoire, et il n'y a pas de cache commun.

Ici, une tâche celery démarrait le batch et mettait à jour le cache contenant les compteurs, mais comme ce cache est différent de celui du processus qui fait tourner django, cela n'avait pas l'effet escompté.

J'ai rencontré ce genre de problèmes à plusieurs reprises, ou j'ai dû jouer l'équilibriste pour utiliser du cache en évitant ce genre de bugs, mais ça devenait trop complexe. J'ai installé memcached, un serveur de cache dédié.

Ça rajoute une dépendance (j'ai mis à jour la doc), mais ce n'est plus possible de faire autrement (à moins de ne plus du tout utiliser de cache et de perdre en performances).

(le ticket n'est pas encore livré).

**Comment by Talengi** [comment]
@thibault OK super. Tu me dis quand tu livres (possible avant 15h ?)

**Comment by Talengi** [comment]
@thibault Je suis connecté en tant que doc controller et j'ai des documents à commenter : les numéros indiquent 3 priorités, 1 en tant que Reviewer, 4 en tant que Leader et 3 en tant que Approver. Pourtant lorsque je rentre dans chaque section, je ne vois pas les mêmes chiffres. Peux-tu s'il te plait regarder ?

**Comment by thibault** [comment]
@Talengi C'était un problème de cache. Ces valeurs sont mises en cache, et mises à jour lorsqu'une revue démarre / est annulée. Mais comme j'ai mis à jour les données sur le serveur avec un nouvel import, le cache était désynchronisé.

J'ai fait en sorte que le processus de livraison vide le cache à chaque fois.

**Comment by Talengi** [comment]
@thibault Peux-tu clarifier le fonctionnement :  est-ce qu'un utilisateur qui voit 0 documents à commenter à 10h00 du matin, peut encore voir 0 à 11h30, alors qu'en fait il a reçu des documents à revoir ? 
Je veux qu'il n'y ait aucun risque que les valeurs entre parenthèses ne changent pas alors qu'en fait la personne reçoit bien des documents.

**Comment by thibault** [comment]
@Talengi Je te confirme que c'est bon. Le cache est mis à jour dans tous les cas.
