### ISSUE TITLE
Affichage du nombre d'items sur le bouton des remarques 

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#57]
Le nombre d'items n'apparait qu'après avoir cliqué sur le bouton.
A corriger pour voir le nombre d'items en permanence.
@thibault

**Comment by thibault** [comment]
@Talengi Problème corrigé, réglé grâce à l'installation de memcached réalisée pour le bug précédent (comme quoi…)

**Comment by thibault** [comment]
@Talengi Je viens de livrer les deux tickets.

**Comment by Talengi** [comment]
@thibault Attends :) Je suis connecté en tant que doc controller, et je vais dans mes revues en tant qu'Approver. Je vais sur le doc FAC09001-CTR-001-TEL-BAS-5530. Le bouton remarks indique 0, mais lorsque je clique dessus, il indique 3. Est du au cache et au rafraichissement ?

**Comment by thibault** [comment]
@Talengi Le cache n'est mis à jour que lors de l'ajout / suppression de commentaires. Ici, comme la fonctionnalité à été livrée sur une base existante, le compteur sera incorrect pour toutes les révisions ayant déjà des commentaires. Il n'y aura pas ce problème sur les projets vierges, ni sur les prochaines livraisons.

Si tu ajoute un commentaire et recharge la page, le compteur devrait s'afficher correctement.

Note que maintenant, la base n'est plus reconstruite après chaque livraison, car ça prends tout simplement trop de temps.

**Comment by Talengi** [comment]
@thibault Je n'arrive pas à ajouter de remarque à présent. Toi aussi ?

**Comment by Talengi** [comment]
@thibault Je précise que ça marche pour un document qui est en revue, mais pas pour le même document qui n'est pas en revue.

**Comment by Talengi** [comment]
@thibault En fait ce que l'on ne gère pas bien aujourd'hui c'est la gestion de l'ajout de remarques. Un utilisateur peut avoir l'impression qu'il peut ajouter une remarque et imaginer un bug, alors qu'il ne devrait pas avoir la possibilité d'ajouter du texte. On laisse comme ça pour le moment et on reprendra plus tard.

**Comment by thibault** [comment]
@Talengi Oui, aujourd'hui il est plus simple d'afficher le formulaire et de renvoyer une erreur plutôt que de réaliser un contrôle à priori. J'ai ouvert le ticket #86 pour qu'on puisse clotûter celui-là.
