### ISSUE TITLE
Gestion des organisations dans les transmittals

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#59]
@thibault La section est aujourd'hui indépendante des organisations et je ne l'ai pas indiqué dans les colonnes du CSV. Mais comment sait-on à quelle organisation les documents sont-ils rattachés ? Ne va-ton pas devant un problème ?

**Comment by Talengi** [comment]
@thibault Rajouter dans les colonnes du CSV les champs "Organisation" et "Category" pour que les transmettais soient bien gérés à ce niveau. Puis mettre à jour les scripts de vérification.

**Comment by thibault** [comment]
@Talengi La manière dont cette liaison va être gérée dépend de la façon dont les Transmittals seront intégrés aux catégories de documents. Cf. https://trello.com/c/a30wn3od/168-integration-du-transmittal-dans-phase

À discuter, donc.
