### ISSUE TITLE
Mise en cohérence du formulaire de documents et du transmittal

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#61]
@thibault Dans la section "Révision" du formulaire de document, peux-tu ajouter le champs "Received date" qui est dans le transmittal ?

**Comment by Talengi** [comment]
@thibault C'est la received date qui est la date de démarrage de la revue. Il faut donc mettre à jour la revue de ce côté là.

**Comment by thibault** [comment]
@Talengi Ce champ a-t-il une valeur par défaut quand le document est créé via un formulaire ? J'imagine que le champ est en lecture seule dans le formulaire ?

**Comment by thibault** [comment]
@Talengi Je précise qu'aujourd'hui, on n'affiche dans la liste des revues que les documents dont la revue a effectivement été démarrée via le formulaire (bouton « start review »).

Ainsi, même si un document a un champ « received_date » enregistré, il n'est pas considéré « en revue » par Phase et ne sera pas affiché dans les listes de revues tant que l'utilisateur n'a pas explicitement lancé la revue.

**Comment by Talengi** [comment]
@thibault On est d'accord, ce que tu décris est le bon fonctionnement.
