### ISSUE TITLE
Problème document number à la création du document

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#64]
@thibault J'ai créé le document FAC10005-CTR-002-CIV-LAY en renseignant les champs qui composent le document number, mais il n'y pas de champ sequential number. Il me semblait pourtant qu'il y était avant, non ? Il est indiqué en champ libre dans le modèle de données.
Tu peux le rajouter dans le formulaire s'il te plait ? Car si on ne créé pas un document en indiquand directement sa référence dans le document number, on obtient alors un numéro incomplet.
 

Merci !

**Comment by thibault** [comment]
@Talengi Le champ sequential number était en effet manquant du formulaire. C'est corrigé.

**Comment by Talengi** [comment]
@thibault Il y a à présent bien le champ, mais il n'est pas pris en compte dans le document number. Peux-tu corriger cela stp ?

**Comment by thibault** [comment]
@Talengi Mea culpa. Ça sera corrigé pour la prochaine livraison.
