### ISSUE TITLE
Ouverture des PDF importés automatiquement

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#66]
@thibault Je n'arrive à ouvrir aucun PDF que tu as importé en automatique.
A chaque fois je tombe sur la page "This is not the page you were looking for."
Tu peux regarder ?

**Comment by thibault** [comment]
Ce ne sont que des fichiers bidons et vides que j'ai généré à la volée pour permettre d'importer les csv. Il faudrait générer une vraie archive contenant tous les pdfs pour que ça puisse fonctionner.
