### ISSUE TITLE
Distribution List dans le formulaire de document

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#68]
@thibault Dans la section "Distribution list" du formulaire, peut-on considérer la règle suivante : 
- si une révision avait une liste de distribution, alors on la conserve par défaut pour les nouvelles révisions. Si aucune liste n'a jamais été spécifiée, on écrit par défaut : "There is no distribution list associated to this document"

Merci !

**Comment by thibault** [comment]
@Talengi livré

**Comment by Talengi** [comment]
@thibault C'est ok, merci !

**Comment by Talengi** [comment]
@thibault Désolé, mais en fait, c'est pas bon, je pense que l'on s'est mal compris.
Ca marche bien lorsque tu édites le doc ou le révises, mais pas quand le formulaire est en lecture seule. Est-ce que tu peux faire apparaitre la liste de distribution aussi lorsque le formulaire est en lecture seule et même si aucune revue n'a élé lancée ? merci

**Comment by thibault** [comment]
@Talengi Pour le moment, il faut que la revue soit en cours pour afficher une liste de distribution. Afficher la même liste sans revue en cours va demander un peu de jonglage. Est-ce qu'on peut mettre ça dans un nouveau ticket, puisqu'il s'agit d'une demande différente ?

**Comment by Talengi** [comment]
@thibault OK je clos ce ticket et je fais une carte Trello pour plus tard.
