### ISSUE TITLE
Les nouveaux documents ne sont pas indexés

### ISSUE THREAD

**Issue by thibault** [Talengi/phase#69]
Les nouveaux documents ne sont pas indexés.

En effet, la tâche celery se lance avant que la transaction n'ait été commité.

**Comment by Talengi** [comment]
@thibault J'ai fermé le ticket #89 pour ne conserver que celui-ci.

**Comment by thibault** [comment]
@Talengi Cette asynchnoricité django / celery posait vraiment trop de problèmes. Je l'ai pour le moment supprimé : l'appel à elasticsearch se fait en même temps que la requête django. On y perd un peu en performances, mais gagne grandement en simplicité.

**Comment by Talengi** [comment]
@thibault C'est OK, merci !
