### ISSUE TITLE
Impossible d'ouvrir le formulaire de revue d'un document en cours de revue

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#71]
@thibault 
J'ai lancé une revue sur le document FAC10005-ABE-500-ELE-CER-0001, mais je n'arrive pas à ouvrir le formulaire de revue, connecté en tant que doc controller, ni en tant que user.
Peux-tu s'il te plait regarder ?

**Comment by thibault** [comment]
@Talengi J'ai tenté là même opération en local, mais j'accède au formulaire sans problèmes avec les trois comptes. Peux-tu me préciser le problème rencontré ?

**Comment by Talengi** [comment]
@thibault Je ne sais pas ce qui s'était passé, mais depuis que tu as refait des livraisons, le problème n'est plus là. Je pense que c'était un bug ou une incohérence avec l'import de masse. J'arrive bien à tout ouvir.
Je ferme ce ticket.
