### ISSUE TITLE
Impossible de lancer une revue sur plusieurs documents en même temps

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#74]
@thibault J'ai essayé de lancer une revue sur trois documents en même temps, mais je n'en vois aucun dans les documents à revoir.
Peux-tu regarder ?

**Comment by thibault** [comment]
@Talengi C'est un problème corrigé hier en même temps qu'un autre bug. Ça marche correctement chez moi maintenant.

**Comment by Talengi** [comment]
@thibault J'ai le bug que je te joins en pièce jointe. Tu peux regarder ?
![batch distributions](https://cloud.githubusercontent.com/assets/4034223/8721987/4a8bf67e-2bc0-11e5-810d-c3e196bd42df.PNG)

**Comment by thibault** [comment]
@Talengi Petit hiatus pendant la livraison. C'est corrigé.

**Comment by Talengi** [comment]
@thibault tu as fait une nouvelle livraison du coup, ou pas encore ?

**Comment by thibault** [comment]
Non, mais ce problème est corrigé.
