### ISSUE TITLE
Documents under review reconnus comme pas under review

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#75]
@thibault on a un souci avec l'import Excel je pense : les valeurs automatiquement remplies via l'excel, ne sont pas forcément reconnues comme réelles par Phase. Du coup, si je cherche des documents qui ne sont pas under review et pas overdue, je ne trouve pas la réalité de ce que Phase entend comme under review ou overdue...Je me trompe ?
Par exemple le document FAC10005-ABE-500-ELE-CER-0001 : il n'est pas under review, pas overdue quand tu fais une recherche et que tu regardes la liste de documents. Mais lorsque tu l'édites ou que tu regardes les tâches à traiter, tu vois que pour Phase, il est en cours de revue.
Peux-tu regarder cela ?

**Comment by thibault** [comment]
@Talengi Les attributs « est en cours de revue » et « est overdue » sont calculés en fonction d'autres champs. Voici le détail des calculs.

Une révision est en cours de revue si la date de début de revue (review_start_date) est configurée, mais pas la date de fin de revue (review_end_date).

Une révision est « overdue » si elle est en cours de revue et si review_due_date < maintenant.

Il se trouve que dans les deux csv importés, aucune colonne ne correspond au champ « review_start_date ». Si on peut soit ajouter la colonne, soit mapper la valeur à partir d'une colonne existante, on obtiendra le résultat escompté.

**Comment by Talengi** [comment]
@thibault C'est le champ "received date" du CSV qui correspond à notre "review_start_date". Oui, fais en sorte que cela fonctionne.

**Comment by thibault** [comment]
@Talengi C'est fait.
