### ISSUE TITLE
Dashboard - Pas de valeurs sur la ligne % of documentss reviewed late by Leader

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#76]
@thibault La ligne "% of documentss reviewed late by Leader" n'a comme valeur que des 0.
Peux-tu regarder ? Est-ce parce que le calcul n'a pas été implémenté ?
Merci.

**Comment by thibault** [comment]
@Talengi Effectivement, les colonnes « Review Transmittal Lead Reviewer Completed On date » et « Review Transmittal Approver Completed On date » ne sont pas importées correctement, et ne sont donc pas reportées correctement dans le modèle de données finales. Je vais corriger ça.

**Comment by thibault** [comment]
@Talengi Quelques complications en ce qui concerne l'import de ces données.

Dans le csv, j'ai deux colonnes pour le commentaire du leader : 
 - son nom
 - la date de son commentaire

Idem pour l'approver.

Dans le modèle de données actuel, les membres de la liste de distribution (reviewers, leader, approver) correspondent à des comptes utilisateurs dans Phase. Un compte est identifié par une adresse email.

Ici, je n'ai que le nom. En supposant que le compte existe déjà, il faudrait donc que je le récupère par ce champ, ce qui n'est pas optimal.

Que se passe-t-il si le compte n'existe pas ? Je ne peux pas le créer sans avoir d'adresse email, à moins d'en générer une bidon.

Peut-on en discuter ?

**Comment by thibault** [comment]
@Talengi Autre souci : dans Phase, pour qu'une revue démarre, il faut que le leader soit obligatoirement spécifié. Or, dans le csv, toutes les revues sont considérées démarrées, mais le leader n'est pas toujours indiqué. Comment doit-on gérer ça ?

**Comment by Talengi** [comment]
@thibault Pour les comptes, ne peut-on pas faire une vérification entre le nom du CSV et la liste des utilisateurs existants dans Phase, afin justement que tout soit cohérent ?

Pour le démarrage des revues : il faut en effet préciser les règles si on veut que cela soit pertinent.
Je propose : 
- Si la colonne "Review Transmittal Sent date" est vide, alors la revue n'est pas démarrée
- Si la colonne "Review Transmittal Sent date" indique une date et que la colonne "Review Transmittal Status" indique "In Commenting", "In Consolidation" ou "In Approval", alors le document est en cours de revue

**Comment by Talengi** [comment]
@thibault Attention à lire avec le ticket #81

**Comment by thibault** [comment]
@Talengi Il reste quelques cas à traiter. Peux-tu m'appeler car ce serait plus simple d'en discuter ?

**Comment by thibault** [comment]
Je récapitule le contenu de la conversation : 

1) Si les colonnes « Review Transmittal Lead Reviewer Name » et / ou « Review Transmittal Approver Name » sont remplies, alors il faut vérifier que les noms correspondent bien à des comptes utilisateurs existants dans Phase avec les bons droits, i.e appartenant à la bonne catégorie. Sinon, soulever une erreur de validation.

2) C'est la colonne « Review Transmittal Sent date » qui correspond au champ « Review start date ».

3) Si la colonne « Review Transmittal Approver Name » est vide et que « Review Transmittal Approver Completed On date » est remplie, c'est simplement qu'il n'y a pas d'approver pour cette revue et qu'on a repris la date correspondant à la revue du leader. C'est aussi la date de fin de la revue.

4) Il n'y a pas d'informations dans le csv concernant de simple reviewers.

5) La colonne « Review Transmittal Status » du csv peut être déduite des autres champs (comme Phase le fait aujourd'hui), et elle est générée automatiquement. Elle peut donc être totalement ignorée par le processus d'import.

**Comment by Talengi** [comment]
@thibault 
1) Oui
2) Oui
3) Oui
4) Oui
5) Oui

**Comment by thibault** [comment]
\o/

@Talengi Dernière (j'espère) question.

Si la colonne « Review Transmittal Sent date » correspond à la date de début de la revue, est-ce qu'on peut considérer que c'est une seule et même valeur ? Ou bien faut-il toujours les gérer séparément ?

**Comment by Talengi** [comment]
@thibault C'est à dire ? Pour moi, c'est bien une seule et même valeur. Je t'appelle ?

**Comment by thibault** [comment]
@Talengi Inutile si c'est bien une seule et même valeur (j'avais ajouté un champ supplémentaire à l'origine). Ça répond à ma question.

**Comment by Talengi** [comment]
@thibault OK

**Comment by Talengi** [comment]
@thibault C'est la galère ou tu t'en sors ?

**Comment by thibault** [comment]
@Talengi Beaucoup de tests à écrire, mais ça avance doucement.

**Comment by thibault** [comment]
@Talengi Bon, c'est traité. Il reste une dernière question.

Aujourd'hui, on fait la distinction entre une revue réellement réalisée par l'utilisateur et une revue cloturée, par exemple par le doc controler.

A priori, dans le csv, on a aucun moyen de faire la distinction entre les deux, non ? Ça va être encore plus empêtant avec les nouveaux codes de retour de la revue définis dans Trello.

Comment doit on gérer l'import :  est-ce qu'on considère que les revues ont été réellement réalisées par les différents utilisateurs, ou on peut juste indiquer que l'étape est cloturée ?

**Comment by Talengi** [comment]
@thibault Je confirme que le CSV ne permet pas de faire la distinction.
Si on ne sait pas via un import, alors on indique simplement que l'étape est cloturée.
Ca te va ?

**Comment by Talengi** [comment]
@thibault Tu pourras faire une livraison des dernières modifs ce soir si tu n'as pas livré hier ?
