### ISSUE TITLE
Gestion du Dashboard dans Phase

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#77]
@thibault 
Est-ce que le dashboard est relié aujourd'hui à une organisation ou est-ce indépendant ?
Si ce n'est pas le cas, il faut que ce soit spécifiquement relié à une organisation.

Du coup dans l'URL il faudrait le relier à l'organisation et simplement l'appeler "Dashboard".

**Comment by thibault** [comment]
@Talengi Je pense qu'il faut qu'on discute de ce ticket, car c'est un poil complexe et il y a quelques trucs à prendre en compte.

La situation aujourd'hui est la suivante : le dashboard travaille avec toutes les données d'un certain type de documents (epc2 > deliverables). On parle bien du type de document, pas de l'organisation / catégorie (cf. ticket #89). Mais le dashboard est défini en dur, donc il apparaitra dans le menu quelque soit la configuration de phase.

Points à considérer : 

 * les permissions se gèrent au niveau de la catégorie, i.e un utilisateur a le droit d'accéder à telle ou telle catégorie, mais il n'y a pas de notion d'accès à une organisation complète.
 * d'un point de vue fonctionnel, le dashboard se situe au niveau de la catégorie : on travaille avec toutes les données d'une catégorie, mais on ne peut pas mélanger les données de plusieurs catégories entre elles.
 * les catégories sont des données définies dans l'admin, alors que pour l'instant le dashboard est défini en dur.

Il faudrait donc : 

 * discuter du ticket #89 et du découpage de Phase en organisations / catégories ;
 * définir de quelle manière un doc controller peut activer un dashboard en admin ;

**Comment by Talengi** [comment]
@thibault 
Gestion des droits du Dashboard : 
- on rattache le dashboard à une organisation
- on donne accès au Dashboard sur le même modèle qu'une catégorie de document : on peut accéder au dashboard, sans accéder aux deliverables et vice et versa
