### ISSUE TITLE
Revue de documents - affichage du chemin

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#78]
@thibault Lorsque tu es Reviewer, Leader ou Approver d'un document, tu ne vois plus dans le chemin que "Review > Document Number"
Est-ce que tu peux ajouter le rôle dans le chemin entre "Review" et le N° de document ?

**Comment by thibault** [comment]
@Talengi Que se passe-t-il si un utilisateur a plusieurs rôles sur une même revue, e.g il est à la fois reviewer et approver ?

**Comment by Talengi** [comment]
@thibault D'un point de vue métier, il n'y pas de raison que cela arrive.
Il y a un point technique qui te bloque ?

**Comment by thibault** [comment]
@Talengi J'ai cru qu'il y en aurait un, mais finalement non.

**Comment by Talengi** [comment]
@thibault ok parfait
