### ISSUE TITLE
Revue de documents - bug sur les mentions dans les remarques

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#79]
@thibault Lorsque tu veux mettre une remarque en mentionnant un utilisateur, la remarque se met en double. Peux-tu regarder ?

**Comment by Talengi** [comment]
@thibault Je précise : la remarque se met en double au moment ou tu la fais, mais une fois que tu as fermé la pop up et que tu rouvres, le compte est bon.

**Comment by Talengi** [comment]
@thibault Autre précision : ce que je décris ci-dessus se fait depuis le formulaire de revue d'un document.
Si tu vas dans la liste de documents et consulte un formulaire général, le bouton "Remarks" n'affiche plus le nombre d'items. Il faut cliquer dessus une fois, afin d'afficher la pop-up et voir que des remaruques ont été faites, pour voir que le nombre d'items s'affiche bien.

**Comment by thibault** [comment]
@Talengi Ce bug a été corrigé en même temps que les autres problèmes liés aux remarques. Ça devrait fonctionner maintenant.

**Comment by Talengi** [comment]
@thibault C'est ok merci
