### ISSUE TITLE
Revue de documents - Statut de la revue

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#81]
@thibault Dans le tableau présentant la liste de distribution et les commentaires, on voit les statuts "Pending" et "Completed".
Peux-tu s'il te plait faire les modifications suivantes : 

Lorsque la revue est à l'étape des Reviewers :  
- Le statut des Reviewers est "In progress" tant que le document n'a pas été traité. Si des commentaires sont faits, le statut est "Reviewed with comments". Si le document a été revu sans commentaires, le statut est "Reviewed without comments". Si le document n'a pas été traité et que le Leader a pris la main, le statut est "Not reviewed"
- Le statut du Leader est "Pending"
- Le statut de l'Approver (si il y en a un) est "Pending"

Lorsque la revue est à l'étape du Leader : 
- Le statut des Reviewers est celui indiqué ci-dessus en fonction des différents cas possibles
- Le statut du Leader est "In progress". Lorsque le Leader a revu le document, le statut indique un des Return Codes possible (cf. Trello, carte "Codes de retour lors de la revue"). Si le Leader n'a pas traité le document car l'Approver a pris la main ou que le Doc Controller a fermé la revue, le statut indique "Not reviewed"
- Le statut de l'Approver indique "Pending"

Lorsque la revue est à l'étape de l'Approver :  
- Le statut des Reviewers est celui indiqué ci-dessus en fonction des différents cas possibles
- Le statut du Leader est celui indiqué ci-dessus en fonction des différents cas possibles
- Le statut de l'Approver est "In progress". Lorsque l'Approver a revu le document, le statut indique un des Return Codes possible (cf. Trello, carte "Codes de retour lors de la revue"). Si l'Approver n'a pas traité le document car le Doc Controller a fermé la revue, le statut indique "Not reviewed"

**Comment by Talengi** [comment]
@thibault Les données/statuts pourront être utilisés ailleurs (dashboard, listes de docs, etc.)

**Comment by Talengi** [comment]
@thibault Je suis short pour faire la daily aujourd'hui et idem pour faire un point aussi ce soir.
Tu peux bosser sur ce ticket + la carte Trello sur les codes retour ?
Tu me dis tout de même en cours de matinée si tu as des questions.
Ca te va ?

**Comment by thibault** [comment]
@Talengi Pas de problèmes. Je suis en train de finir ce ticket. J'attaque les codes retours juste après, et j'embraye sur les optimisations de perfs restantes.

Une question toutefois : 

pour les révisions déjà présentes en base, les statuts ne seront pas corrects (tous les statuts seront à « pending » par défaut). Est-ce que ça vaut le coup que je lance un réimport pour mettre à jour les données, ou on s'en fiche pour le moment ?

**Comment by Talengi** [comment]
@thibault Si tu peux relancer un import c'est bien. Et si tu dois déborder sur des jours à venir tu me dis.
