### ISSUE TITLE
Révision de document - Champ Class

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#87]
@thibault Lorsque tu révises un document, le champ class ne conserve pas la valeur de la révision N-1.
Peux-tu s'il te plait regarder ?
Merci !

**Comment by thibault** [comment]
@Talengi Lors de la création d'une nouvelle révision, tous les champs du formulaire de révision sont laissés vide pour forcer l'utilisateur à les remplir à nouveau.

Ici, le champ « class » n'échappe pas à la règle. Mais comme il s'agit d'une liste, le premier choix est automatiquement sélectionné.

Deux solutions :

 1) soit on récupère automatiquement la classe de la révision précédente ;
 2) soit on ajoute une valeur vide dans la liste de sélection de la classe pour forcer l'utilisateur à saisir manuellement une valeur, ce qui est plus cohérent avec le fonctionnement du formulaire.

Peux-tu me confirmer la solution que tu préfères ?

**Comment by Talengi** [comment]
@thibault Lorsque l'on révise un document, tous les champs de la révision précédente doivent être récupérés. Si l'utilisateur a une modification à faire, il l'a fera, mais si il n'a pas ou peu de modifications, il gagnera du temps.

**Comment by thibault** [comment]
@Talengi Ok. Tu me confirmes qu'on récupère *tous* les champs de la révision précédente ? Ça vaut aussi pour les documents natifs et pdfs ?

**Comment by Talengi** [comment]
@thibault Tu as raison, désolé, il faut préciser.
Non pas les fichiers associés tels natifs et PDF ou commentaires. Uniquement les metadonnées des sections suivantes : 
- General information
- Related documents
- Schedule
- Distribution list

Pour les metadonnées de la section Revision : 
- "Revision Date" est vide
- "Created on" est rempli automatiquement
- "Class" est repris de la révision précédente
- "Status" est vide
- "Is final revision?" est vide

La section "Review" reste gérée automatiquement par l'application.

J'espère que ça te parait clair. Tu me dis si tu as besoin de clarifier par téléphone.
