### ISSUE TITLE
Revue de document - Incohérence entre formulaire et liste de documents

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#88]
@thibault Le document FAC09001-CTR-001-ROT-BAS-8740 est en cours de revue lorsque tu regardes le formulaire, mais pas lorsque tu regardes la liste de documents.
Peux-ty voir cela stp ?
merci !

**Comment by thibault** [comment]
@Talengi Le problème n'apparait plus après les différentes mises à jour, mais était vraissemblablement provoqué par #69.
