### ISSUE TITLE
Fuite de documents entre organisations

### ISSUE THREAD

**Issue by thibault** [Talengi/phase#89]
Je créée deux organisations « X1 » et « X2 ».

Dans chaque organisation, je créé une catégorie pour le même type de documents, par exemple « X1 > Contractor Deliverable » et « X2 > Contractor Deliverable ».

Si je créé un document dans la première catégorie, il sera visible dans la deuxième, et vice-versa.

**Comment by thibault** [comment]
@Talengi Bon, j'ai cru que ça allait être assez complexe, mais ça n'a finalement pas nécessité plus de quelques caractères. Tant mieux.

Attention, ça ne sera pas visible tant que je n'aurai pas tout réindexé en prod.

**Comment by Talengi** [comment]
@thibault OK merci.
