### ISSUE TITLE
Mise à jour version Django

### ISSUE THREAD

**Issue by thibault** [Talengi/phase#90]
La version de Django utilisée par Phase (1.6) a actuellement deux versions majeures de retard sur la version stable (1.8).

À la sortie de la prochaine version stable (1.9), la 1.6 ne sera plus supportée et ne recevra plus les maj de sécurité.

Par ailleurs, des modifications de librairies intervenues dans les dernières sous versions de la 1.6 font que les dernières mises à jour ne peuvent être appliquées directement.

Il y a donc un certain travail nécessaire pour mettre à jour Django.

**Comment by Talengi** [comment]
@thibault OK pour la semaine prochaine, en plus du travail sur les perfs, nginx, etc.

**Comment by Talengi** [comment]
@thibault Il faudra également penser aux versions de PostgreSQL, Bootstrap, etc.

**Comment by Talengi** [comment]
@thibault Je n'arrive plus à me connecter...:)

**Comment by Talengi** [comment]
@thibault Je n'ai rien dit, au temps pour moi !

**Comment by thibault** [comment]
Bon, la version de Django est livrée, et les tests passent.

En revanche, étant donné l'ampleur des changements, il est fort possible que des bugs soient passés à travers les mailles du filet. Il ne faut donc pas hésiter à rapporter le moindre problème lors de tests manuels.
