### ISSUE TITLE
Probleme start review depuis la liste de documents

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#91]
@thibault J'ai essayé de lancer une revue depuis la liste de documents sur un doc et ça ne marchait pas, alors que depuis le formulaire ça marchait.
Peux-tu regarder ?

**Comment by Talengi** [comment]
@thibault Tu me dis si tu as besoin de faire un point ou pas ce matin ?

**Comment by thibault** [comment]
@Talengi Rien de neuf depuis vendredi soir, je continue sur ma lancée.

**Comment by Talengi** [comment]
@thibault Tu me dis si tu as besoin d'un point.

**Comment by thibault** [comment]
@Talengi C'est bon pour moi. En fin de journée ?

**Comment by Talengi** [comment]
@thibault Fin de journée va être compliquée pour moi, donc plutôt 15h si possible pour toi. Est-ce que tu as fait une livraison ou pas encore ?

**Comment by thibault** [comment]
@Talengi Ok pour 15h. Je viens de terminer une livraison. La principale modif concerne les dashboards. Il y a un nouveau module correspond dans l'admin.

Je te laisse regarder et on en discute tout à l'heure.
