### ISSUE TITLE
Menu Dashboard inactif

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#92]
@thibault Suite à la dernière livraison, le menu Dashboard est incatif. Peux-tu s'il te plait rectifier ?

**Comment by thibault** [comment]
@Talengi Il y a quelques trucs à savoir, j'aurais du le préciser.

Pour créer un dashboard, [il faut aller dans l'admin à la section dashboards](http://phase.clients.jouannic.fr/admin/dashboards/dashboard/).

Au moment de l'édition du dashboard, il faut choisir la liste des utilisateurs qui auront accès au dashboard.

Dans le menu dashboard, seul les dashboards autorisés apparaissent.

Par ailleurs, pour des raisons de performances, il y a un cache de plusieurs minutes qui fait que les modifications n'apparaissent pas tout de suite.

Je te propose d'en discuter tout à l'heure.

**Comment by Talengi** [comment]
@thibault Pour moi ce ticket est OK donc je vais le clore.
Tu veux faire un point d'ici 30mn ou rien de nouveau pour le moment ?

**Comment by thibault** [comment]
Je bosse toujours sur la migration django 1.8. C'est globalement
terminé à part un ou deux points récalcitrants. On fait un point si tu
penses que c'est nécessaire.

Cordialement,
--
Thibault Jouannic
Ingénieur Web Freelance
http://miximum.fr
+33 6 30 47 30 50

**Comment by Talengi** [comment]
@thibault Non pas de souci, je te laisse continuer et tu me dis si tu arrives à finir ce soir.

**Comment by Talengi** [comment]
@thibault Tu es toujours sur la migration ou de retour sur les tickets ?

**Comment by thibault** [comment]
@Talengi Finalement terminé ce soir la migration. Beaucoup de bugs à corriger. L'avantage est que j'ai corrigé tous les tests (à l'exception d'un ou deux qui restent en suspens).

On a déjà quelques gains en performances et beaucoup de gains en qualité.

Je reprends les tickets demain.
