### ISSUE TITLE
Problèmes avec la fonction de liens entre documents

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#98]
@thibault Sur Mac/Safari, lorsque je suis dans le formulaire de document, que j'édite la dernière version, que je clique sur le menu déroulant "Related documents", l'écran se fige, ça rame et au bout de presque 10 secondes, je peux sélectionner des documents.
Peux-tu regarder cela s'il te plait ? Merci.

**Comment by thibault** [comment]
Pour info, c'est lié aux tickets #22 et #85

**Comment by thibault** [comment]
@Talengi J'ai supprimé le widget d'autocomplete utilisé pour les "related documents", ce qui résoud déjà le ticket #22.

Maintenant, il reste à écrire un vrai widget d'autocomplete multi-usage, et c'est quelque chose qui peut prendre deux ou trois jours (sauf si j'arrive à en trouver un qui fonctionne enfin correctement). 

Je ne sais pas dans quelle mesure c'est une priorité pour toi. Je laisse de côté pour passer à la suite, et on en discute quand tu veux / peux.

**Comment by Talengi** [comment]
@thibault Oui laisse de côté pour le moment et on voit cela ensuite. On traite d'abord les autres tickets et le Trello. Merci !
