### ISSUE TITLE
Bug avec les remarques

### ISSUE THREAD

**Issue by Talengi** [Talengi/phase#99]
@thibault Sur le document FAC09001-CTR-001-PRT-LAY-0186, lorsque j'essaye d'ajouter une remarque, j'obtiens le message suivant : There was a problem submitting your message.
Tu peux regarder s'il te plait ?
Merci.

**Comment by Talengi** [comment]
@thibault Je précise que si tu démarres une revue avec remarque, la fonction marche bien.

**Comment by Talengi** [comment]
@thibault Mettre le message d'erreur suivant : "Remarks can be added when the document is under review"

**Comment by thibault** [comment]
@Talengi J'ai dit une bêtise, ce problème a déjà été corrigé plus tôt, le formulaire n'apparait plus quand on ne peut pas commenter. Je pense que ce problème est lié aux autres « woops » que je viens de corriger. En tout cas je ne reproduits plus.

**Comment by Talengi** [comment]
@thibault Ok tu as moyen de faire une livraison avec les dernieres corrections stp ?

**Comment by thibault** [comment]
Oui, c'est fait.
